Repository prebid/prebid-server-java, pull requests merged in 2023-02, with the labels that each got.

#2137 Tests: Migrate stored, amp, cache tests to generic
  src/test/java/org/prebid/server/it/ApplicationTest.java
  src/test/resources/org/prebid/server/it/amp/test-amp-response.json
  src/test/resources/org/prebid/server/it/amp/test-cache-request.json
  src/test/resources/org/prebid/server/it/amp/test-generic-bid-request.json
  src/test/resources/org/prebid/server/it/amp/test-generic-bid-response.json
  src/test/resources/org/prebid/server/it/amp/test-genericAlias-bid-request.json
  src/test/resources/org/prebid/server/it/amp/test-genericAlias-bid-response.json
  src/test/resources/org/prebid/server/it/amp/test-rubicon-bid-request.json
  src/test/resources/org/prebid/server/it/cache/update/test-auction-request.json
  src/test/resources/org/prebid/server/it/cache/update/test-auction-response.json
  src/test/resources/org/prebid/server/it/cache/update/test-generic-bid-request1.json
  src/test/resources/org/prebid/server/it/cache/update/test-generic-bid-response1.json
  src/test/resources/org/prebid/server/it/cache/update/test-genericAlias-bid-request2.json
  src/test/resources/org/prebid/server/it/cache/update/test-genericAlias-bid-response2.json
  src/test/resources/org/prebid/server/it/cache/update/test-rubicon-bid-request1.json
  src/test/resources/org/prebid/server/it/cache/update/test-rubicon-bid-request2.json
  src/test/resources/org/prebid/server/it/cache/update/test-update-settings-request.json
  src/test/resources/org/prebid/server/it/openrtb2/storedresponse/test-auction-request.json
  src/test/resources/org/prebid/server/it/openrtb2/storedresponse/test-auction-response.json
  src/test/resources/org/prebid/server/it/storedimps/test-generic-stored-imp-cache-update.json
  src/test/resources/org/prebid/server/it/storedimps/test-genericAlias-stored-video-cache-update.json
Labels: do not port

#2140 Update cross-repo-issue.yml for omit `tests` label
  .github/workflows/cross-repo-issue.yml
Labels: enhancement, do not port

#2145 Functional tests for `<bidder>.usersync.enabled` property
  src/test/groovy/org/prebid/server/functional/tests/UserSyncSpec.groovy
Labels: tests

#2150 Rubicon: Fix user.ext properties population
  src/main/java/org/prebid/server/bidder/rubicon/RubiconBidder.java
  src/test/java/org/prebid/server/bidder/rubicon/RubiconBidderTest.java
Labels: do not port

#2148 Refactoring. Move media type processor
  src/main/java/org/prebid/server/auction/ExchangeService.java
Labels: do not port

#2156 KiviAds: Add adapter
  src/main/java/org/prebid/server/bidder/kiviads/KiviAdsBidder.java
  src/main/java/org/prebid/server/bidder/kiviads/proto/KiviAdsImpExtBidder.java
  src/main/java/org/prebid/server/proto/openrtb/ext/request/kiviads/ExtImpKiviAds.java
  src/main/java/org/prebid/server/spring/config/bidder/KiviAdsBidderConfiguration.java
  src/main/resources/bidder-config/kiviads.yaml
  src/main/resources/static/bidder-params/kiviads.json
  src/test/java/org/prebid/server/bidder/kiviads/KiviAdsBidderTest.java
  src/test/java/org/prebid/server/it/KiviAdsTest.java
  src/test/resources/org/prebid/server/it/openrtb2/kiviads/test-auction-kiviads-request.json
  src/test/resources/org/prebid/server/it/openrtb2/kiviads/test-auction-kiviads-response.json
  src/test/resources/org/prebid/server/it/openrtb2/kiviads/test-kiviads-bid-request.json
  src/test/resources/org/prebid/server/it/openrtb2/kiviads/test-kiviads-bid-response.json
  src/test/resources/org/prebid/server/it/test-application.properties
Labels: do not port

#2195 Tests: Create a wrapper for IAB GPP library
  src/test/groovy/org/prebid/server/functional/util/privacy/gpp/GppConsent.groovy
  src/test/groovy/org/prebid/server/functional/util/privacy/gpp/TcfEuV2Consent.groovy
  src/test/groovy/org/prebid/server/functional/util/privacy/gpp/UspV1Consent.groovy
Labels: tests
