Repository prebid/prebid-server-java, pull requests merged in 2023-12, with the labels that each got.

#2810 Tests: Forward low entropy client hints to bidders
  src/test/groovy/org/prebid/server/functional/testcontainers/scaffolding/Bidder.groovy
  src/test/groovy/org/prebid/server/functional/tests/HeaderSpec.groovy
Labels: tests

#2791 Test for configurable targeting prefix
  src/test/groovy/org/prebid/server/functional/model/request/auction/Targeting.groovy
  src/test/groovy/org/prebid/server/functional/tests/TargetingSpec.groovy
Labels: tests

#2751 Test: `Topics in headers`
  src/test/groovy/org/prebid/server/functional/model/request/SecBrowsingTopic.groovy
  src/test/groovy/org/prebid/server/functional/model/request/auction/Data.groovy
  src/test/groovy/org/prebid/server/functional/model/request/auction/ExtData.groovy
  src/test/groovy/org/prebid/server/functional/testcontainers/PbsConfig.groovy
  src/test/groovy/org/prebid/server/functional/tests/TopicsHeaderSpec.groovy
  src/test/groovy/org/prebid/server/functional/util/HttpUtil.groovy
Labels: tests

#2797 Appnexus: Update bidder
  src/main/java/org/prebid/server/bidder/appnexus/AppnexusBidder.java
  src/main/java/org/prebid/server/bidder/appnexus/SameValueValidator.java
  src/main/java/org/prebid/server/bidder/appnexus/model/ImpWithExtProperties.java
  src/main/java/org/prebid/server/bidder/appnexus/proto/AppnexusBidExtAppnexus.java
  src/main/java/org/prebid/server/bidder/appnexus/proto/AppnexusImpExt.java
  src/main/java/org/prebid/server/bidder/appnexus/proto/AppnexusImpExtAppnexus.java
  src/main/java/org/prebid/server/bidder/appnexus/proto/AppnexusKeyVal.java
  src/main/java/org/prebid/server/bidder/appnexus/proto/AppnexusReqExtAppnexus.java
  src/main/java/org/prebid/server/proto/openrtb/ext/request/appnexus/ExtImpAppnexus.java
  src/main/resources/bidder-config/adtelligent.yaml
  src/main/resources/bidder-config/appnexus.yaml
  src/main/resources/static/bidder-params/appnexus.json
  src/test/java/org/prebid/server/bidder/appnexus/AppnexusBidderTest.java
  src/test/java/org/prebid/server/it/AppnexusVideoTest.java
  src/test/resources/org/prebid/server/it/openrtb2/appnexus/test-video-appnexus-bid-request-1.json
  src/test/resources/org/prebid/server/it/openrtb2/appnexus/test-video-appnexus-bid-request-2.json
  src/test/resources/org/prebid/server/it/openrtb2/appnexus/test-video-appnexus-bid-response-1.json
  src/test/resources/org/prebid/server/it/openrtb2/appnexus/test-video-appnexus-bid-response-2.json
  src/test/resources/org/prebid/server/it/openrtb2/appnexus/test-video-appnexus-request.json
  src/test/resources/org/prebid/server/it/openrtb2/appnexus/test-video-appnexus-response.json
  src/test/resources/org/prebid/server/it/openrtb2/appnexus/test-video-cache-request.json
  src/test/resources/org/prebid/server/it/openrtb2/appnexus/test-video-cache-response-matcher.json
  src/test/resources/org/prebid/server/it/test-application.properties
Labels: do not port

#2793 Test: Filter multi format impressions
  src/test/groovy/org/prebid/server/functional/model/config/AccountAuctionConfig.groovy
  src/test/groovy/org/prebid/server/functional/model/request/auction/GenericPreferredBidder.groovy
  src/test/groovy/org/prebid/server/functional/model/request/auction/Prebid.groovy
  src/test/groovy/org/prebid/server/functional/model/request/auction/PreferredBidders.groovy
  src/test/groovy/org/prebid/server/functional/model/response/auction/MediaType.groovy
  src/test/groovy/org/prebid/server/functional/tests/FilterMultiFormatSpec.groovy
Labels: tests

#2769 Configurable targeting prefix
  src/main/java/org/prebid/server/auction/BidResponseCreator.java
  src/main/java/org/prebid/server/auction/TargetingKeywordsCreator.java
  src/main/java/org/prebid/server/auction/VideoResponseFactory.java
  src/main/java/org/prebid/server/handler/openrtb2/AmpHandler.java
  src/main/java/org/prebid/server/proto/openrtb/ext/request/ExtRequestTargeting.java
  src/main/java/org/prebid/server/settings/model/AccountTargetingConfig.java
  src/main/java/org/prebid/server/validation/RequestValidator.java
  src/test/groovy/org/prebid/server/functional/model/request/auction/Targeting.groovy
  src/test/groovy/org/prebid/server/functional/tests/TargetingSpec.groovy
  src/test/java/org/prebid/server/auction/TargetingKeywordsCreatorTest.java
  src/test/java/org/prebid/server/validation/RequestValidatorTest.java
Labels: feature, do not port

#2808 Test: price granularity
  src/test/groovy/org/prebid/server/functional/model/request/auction/Range.groovy
  src/test/groovy/org/prebid/server/functional/tests/TargetingSpec.groovy
Labels: tests

#2823 FreewheelSSP bidder updates
  src/main/java/org/prebid/server/bidder/freewheelssp/FreewheelSSPBidder.java
  src/main/java/org/prebid/server/proto/openrtb/ext/request/freewheelssp/ExtImpFreewheelSSP.java
  src/main/resources/bidder-config/freewheelssp.yaml
  src/main/resources/static/bidder-params/freewheelssp.json
  src/test/java/org/prebid/server/bidder/freewheelssp/FreewheelSSPBidderTest.java
Labels: do not port

#2781 Optional "bidresponse.ext.prebid.targeting" response block
  src/main/java/org/prebid/server/auction/BidResponseCreator.java
  src/main/java/org/prebid/server/validation/RequestValidator.java
  src/test/groovy/org/prebid/server/functional/model/request/auction/Targeting.groovy
  src/test/groovy/org/prebid/server/functional/tests/TargetingSpec.groovy
  src/test/java/org/prebid/server/auction/BidResponseCreatorTest.java
  src/test/java/org/prebid/server/validation/RequestValidatorTest.java
Labels: do not port

#2829 Tests: AMP Targeting FPD
  src/test/groovy/org/prebid/server/functional/tests/AmpFpdSpec.groovy
  src/test/groovy/org/prebid/server/functional/util/HttpUtil.groovy
Labels: tests

#2832 Huawei bidder updates
  src/main/java/com/iab/openrtb/request/VideoObject.java
  src/main/java/com/iab/openrtb/response/Asset.java
  src/main/java/org/prebid/server/bidder/huaweiads/HuaweiAdSlotBuilder.java
  src/main/java/org/prebid/server/bidder/huaweiads/HuaweiAdmBuilder.java
  src/test/java/org/prebid/server/bidder/huaweiads/HuaweiAdSlotBuilderTest.java
  src/test/java/org/prebid/server/bidder/huaweiads/HuaweiAdmBuilderTest.java
  src/test/java/org/prebid/server/bidder/huaweiads/HuaweiAdsBidderTest.java
  src/test/resources/org/prebid/server/it/openrtb2/huaweiads/native_include_video/test-huaweiads-bid-request.json
  src/test/resources/org/prebid/server/it/openrtb2/huaweiads/native_single_image/test-huaweiads-bid-request.json
  src/test/resources/org/prebid/server/it/openrtb2/huaweiads/native_three_image/test-huaweiads-bid-request.json
  src/test/resources/org/prebid/server/it/openrtb2/huaweiads/native_three_image_include_icon/test-huaweiads-bid-request.json
Labels: do not port

#2792 Additional metric for account fetch failed case
  src/main/java/org/prebid/server/auction/requestfactory/Ortb2RequestFactory.java
  src/main/java/org/prebid/server/metric/MetricName.java
  src/main/java/org/prebid/server/metric/Metrics.java
  src/test/java/org/prebid/server/auction/requestfactory/Ortb2RequestFactoryTest.java
  src/test/java/org/prebid/server/metric/MetricsTest.java
Labels: do not port

#2807 IX: bidder response enriched with FledgeAuctionConfig
  src/main/java/org/prebid/server/bidder/ix/IxBidder.java
  src/main/java/org/prebid/server/bidder/ix/model/response/IxBidResponse.java
  src/main/java/org/prebid/server/bidder/ix/model/response/IxExtBidResponse.java
  src/test/java/org/prebid/server/bidder/ix/IxBidderTest.java
Labels: do not port

#2847 Tests: Bidders to generic aliases
  src/test/groovy/org/prebid/server/functional/testcontainers/PbsConfig.groovy
Labels: tests

#2802 Price Granularity: Fix calculation formula
  src/main/java/org/prebid/server/auction/CpmRange.java
  src/main/java/org/prebid/server/proto/openrtb/ext/request/ExtGranularityRange.java
  src/test/groovy/org/prebid/server/functional/model/request/auction/Range.groovy
  src/test/groovy/org/prebid/server/functional/tests/TargetingSpec.groovy
  src/test/java/org/prebid/server/auction/CpmRangeTest.java
Labels: do not port

#2850 Test: Increase coverage for targeting
  src/test/groovy/org/prebid/server/functional/model/request/amp/Targeting.groovy
  src/test/groovy/org/prebid/server/functional/model/request/auction/ImpExtContextData.groovy
  src/test/groovy/org/prebid/server/functional/tests/TargetingSpec.groovy
Labels: tests

#2825 Test: Increase tests coverage for `schain`
  src/test/groovy/org/prebid/server/functional/tests/SchainSpec.groovy
Labels: tests

#2862 Taboola bidder adapter change endpoint
  src/main/resources/bidder-config/taboola.yaml
Labels: do not port

#2818 Remove Legacy UIDs From Cookie
  src/main/java/org/prebid/server/cookie/UidsCookieService.java
  src/main/java/org/prebid/server/cookie/proto/Uids.java
  src/test/java/org/prebid/server/cookie/UidsCookieServiceTest.java
  src/test/java/org/prebid/server/it/ApplicationTest.java
  src/test/java/org/prebid/server/it/DealsTest.java
  src/test/java/org/prebid/server/it/PrematureReturnTest.java
Labels: PBS 3.0

#2864 Add usersync url for the Evtech
  src/main/resources/bidder-config/limelightDigital.yaml
Labels: do not port

#2856 Change dxkulture domain
  src/main/resources/bidder-config/dxkulture.yaml
Labels: do not port

#2866 Indicue: Add adapter
  src/main/resources/bidder-config/adtelligent.yaml
  src/test/java/org/prebid/server/it/IndicueTest.java
  src/test/resources/org/prebid/server/it/openrtb2/indicue/test-auction-indicue-request.json
  src/test/resources/org/prebid/server/it/openrtb2/indicue/test-auction-indicue-response.json
  src/test/resources/org/prebid/server/it/openrtb2/indicue/test-indicue-bid-request.json
  src/test/resources/org/prebid/server/it/openrtb2/indicue/test-indicue-bid-response.json
  src/test/resources/org/prebid/server/it/test-application.properties
Labels: do not port
