Repository prebid/prebid-server-java, pull requests merged in 2023-04, with the labels that each got.

#2002 Core: Add mechanism for applying different retry strategies
  src/main/java/org/prebid/server/execution/RemoteFileSyncer.java
  src/main/java/org/prebid/server/execution/retry/ExponentialBackoffRetryPolicy.java
  src/main/java/org/prebid/server/execution/retry/FixedIntervalRetryPolicy.java
  src/main/java/org/prebid/server/execution/retry/NonRetryable.java
  src/main/java/org/prebid/server/execution/retry/RetryPolicy.java
  src/main/java/org/prebid/server/execution/retry/Retryable.java
  src/main/java/org/prebid/server/spring/config/GeoLocationConfiguration.java
  src/test/java/org/prebid/server/execution/RemoteFileSyncerTest.java
Labels: enhancement, refactoring

#2236 AppNexus: Accept placementId as int or string
  src/main/java/org/prebid/server/bidder/appnexus/AppnexusBidder.java
  src/main/java/org/prebid/server/proto/openrtb/ext/request/appnexus/ExtImpAppnexus.java
  src/main/resources/static/bidder-params/appnexus.json
  src/test/java/org/prebid/server/bidder/appnexus/AppnexusBidderTest.java
Labels: do not port

#2208 Taboola: Add new adapter
  src/main/java/org/prebid/server/bidder/taboola/TaboolaBidder.java
  src/main/java/org/prebid/server/proto/openrtb/ext/request/taboola/ExtImpTaboola.java
  src/main/java/org/prebid/server/spring/config/bidder/TaboolaConfiguration.java
  src/main/resources/bidder-config/taboola.yaml
  src/main/resources/static/bidder-params/taboola.json
  src/test/java/org/prebid/server/bidder/taboola/TaboolaBidderTest.java
  src/test/java/org/prebid/server/it/TaboolaTest.java
  src/test/resources/org/prebid/server/it/openrtb2/taboola/test-auction-taboola-request.json
  src/test/resources/org/prebid/server/it/openrtb2/taboola/test-auction-taboola-response.json
  src/test/resources/org/prebid/server/it/openrtb2/taboola/test-taboola-bid-request-banner.json
  src/test/resources/org/prebid/server/it/openrtb2/taboola/test-taboola-bid-request-native.json
  src/test/resources/org/prebid/server/it/openrtb2/taboola/test-taboola-bid-response-banner.json
  src/test/resources/org/prebid/server/it/openrtb2/taboola/test-taboola-bid-response-native.json
  src/test/resources/org/prebid/server/it/test-application.properties
Labels: do not port

#2271 Tests: fix connection exhaustion issue
  src/test/groovy/org/prebid/server/functional/testcontainers/Dependencies.groovy
  src/test/groovy/org/prebid/server/functional/testcontainers/PbsServiceFactory.groovy
  src/test/groovy/org/prebid/server/functional/testcontainers/container/NetworkServiceContainer.groovy
  src/test/groovy/org/prebid/server/functional/testcontainers/container/PrebidServerContainer.groovy
  src/test/groovy/org/prebid/server/functional/tests/AuctionSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/BaseSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/BidValidationSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/CacheSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/MetricsSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/pg/ReportSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/privacy/GdprAmpSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/privacy/GdprAuctionSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/privacy/PrivacyBaseSpec.groovy
  src/test/resources/org/prebid/server/functional/mysql_config_override.cnf
Labels: tests

#2252 Infytv: Added new bidder
  src/main/java/org/prebid/server/bidder/infytv/InfytvBidder.java
  src/main/java/org/prebid/server/spring/config/bidder/InfytvConfiguration.java
  src/main/resources/bidder-config/infytv.yaml
  src/main/resources/static/bidder-params/infytv.json
  src/test/java/org/prebid/server/bidder/infytv/InfytvBidderTest.java
  src/test/java/org/prebid/server/it/InfytvTest.java
  src/test/resources/org/prebid/server/it/openrtb2/infytv/test-auction-infytv-request.json
  src/test/resources/org/prebid/server/it/openrtb2/infytv/test-auction-infytv-response.json
  src/test/resources/org/prebid/server/it/openrtb2/infytv/test-infytv-bid-request-1.json
  src/test/resources/org/prebid/server/it/openrtb2/infytv/test-infytv-bid-response-1.json
  src/test/resources/org/prebid/server/it/test-application.properties
Labels: do not port

#2237 Globalsun: Add new bidder
  src/main/java/org/prebid/server/bidder/globalsun/GlobalsunBidder.java
  src/main/java/org/prebid/server/bidder/globalsun/model/GlobalsunImpExtBidder.java
  src/main/java/org/prebid/server/proto/openrtb/ext/request/globalsun/ExtImpGlobalsun.java
  src/main/java/org/prebid/server/spring/config/bidder/GlobalsunConfiguration.java
  src/main/resources/bidder-config/globalsun.yaml
  src/main/resources/static/bidder-params/globalsun.json
  src/test/java/org/prebid/server/bidder/globalsun/GlobalsunBidderTest.java
  src/test/java/org/prebid/server/it/GlobalsunTest.java
  src/test/resources/org/prebid/server/it/openrtb2/globalsun/test-auction-globalsun-request.json
  src/test/resources/org/prebid/server/it/openrtb2/globalsun/test-auction-globalsun-response.json
  src/test/resources/org/prebid/server/it/openrtb2/globalsun/test-globalsun-bid-request.json
  src/test/resources/org/prebid/server/it/openrtb2/globalsun/test-globalsun-bid-response.json
  src/test/resources/org/prebid/server/it/test-application.properties
Labels: do not port

#2282 Madvertise: Updated contact email address
  src/main/resources/bidder-config/madvertise.yaml
Labels: do not port

#2281 Impactify: Updated contact email address
  src/main/resources/bidder-config/impactify.yaml
Labels: do not port

#2247 Adnuntius: Added dealId field
  src/main/java/org/prebid/server/bidder/adnuntius/AdnuntiusBidder.java
  src/main/java/org/prebid/server/bidder/adnuntius/model/response/AdnuntiusAd.java
  src/test/java/org/prebid/server/bidder/adnuntius/AdnuntiusBidderTest.java
  src/test/resources/org/prebid/server/it/openrtb2/adnuntius/test-adnuntius-bid-response.json
  src/test/resources/org/prebid/server/it/openrtb2/adnuntius/test-auction-adnuntius-response.json
Labels: do not port

#2265 Evtech: Added new bidder
  src/main/java/org/prebid/server/bidder/limelightdigital/LimeLightDigitalBidder.java
  src/main/resources/bidder-config/limelightDigital.yaml
  src/test/java/org/prebid/server/bidder/limelightdigital/LimeLightDigitalBidderTest.java
  src/test/resources/org/prebid/server/it/test-application.properties
Labels: do not port

#2278 Pwbid: Add new bidder
  src/main/java/org/prebid/server/bidder/pwbid/PwbidBidder.java
  src/main/java/org/prebid/server/spring/config/bidder/PwbidConfiguration.java
  src/main/resources/bidder-config/pwbid.yaml
  src/main/resources/static/bidder-params/pwbid.json
  src/test/java/org/prebid/server/bidder/pwbid/PwbidBidderTest.java
  src/test/java/org/prebid/server/it/PwbidTest.java
  src/test/resources/org/prebid/server/it/openrtb2/pwbid/test-auction-pwbid-request.json
  src/test/resources/org/prebid/server/it/openrtb2/pwbid/test-auction-pwbid-response.json
  src/test/resources/org/prebid/server/it/openrtb2/pwbid/test-pwbid-bid-request.json
  src/test/resources/org/prebid/server/it/openrtb2/pwbid/test-pwbid-bid-response.json
  src/test/resources/org/prebid/server/it/test-application.properties
Labels: do not port

#2126 Tests: Add alias functional tests
  src/test/groovy/org/prebid/server/functional/tests/AliasSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/BidValidationSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/BidderParamsSpec.groovy
Labels: tests

#2269 Adtrgtme: Added siteId
  src/main/java/org/prebid/server/bidder/adtrgtme/AdtrgtmeBidder.java
  src/main/java/org/prebid/server/proto/openrtb/ext/request/adtrgtme/ExtImpAdtrgtme.java
  src/main/resources/static/bidder-params/adtrgtme.json
  src/test/java/org/prebid/server/bidder/adtrgtme/AdtrgtmeBidderTest.java
  src/test/java/org/prebid/server/it/AdtrgtmeTest.java
  src/test/resources/org/prebid/server/it/openrtb2/adtrgtme/test-adtrgtme-bid-request.json
  src/test/resources/org/prebid/server/it/openrtb2/adtrgtme/test-auction-adtrgtme-request.json
Labels: do not port

#2280 Taboola: Support insensitive tagId, gvlID
  src/main/java/org/prebid/server/bidder/taboola/TaboolaBidder.java
  src/main/java/org/prebid/server/proto/openrtb/ext/request/taboola/ExtImpTaboola.java
  src/main/java/org/prebid/server/spring/config/bidder/TaboolaConfiguration.java
  src/test/java/org/prebid/server/bidder/taboola/TaboolaBidderTest.java
  src/test/resources/org/prebid/server/it/openrtb2/taboola/test-auction-taboola-response.json
  src/test/resources/org/prebid/server/it/openrtb2/taboola/test-taboola-bid-response-banner.json
  src/test/resources/org/prebid/server/it/openrtb2/taboola/test-taboola-bid-response-native.json
Labels: do not port

#2314 Tests: Add functional fix for circumvent generic alias
  src/test/groovy/org/prebid/server/functional/testcontainers/PbsConfig.groovy
  src/test/groovy/org/prebid/server/functional/tests/BidderParamsSpec.groovy
Labels: tests
