Repository prebid/prebid-server-java, pull requests merged in 2024-12, with the labels that each got.

#3584 Tests: `plcmt` logic to bidadjustment mediatype
  src/test/groovy/org/prebid/server/functional/tests/BidAdjustmentSpec.groovy
Labels: tests

#3558 Test: default bids cache ttl
  src/test/groovy/org/prebid/server/functional/tests/BidExpResponseSpec.groovy
Labels: tests

#3561 Sharethrough: declare support for oRTB 2.6
  src/main/resources/bidder-config/sharethrough.yaml
  src/test/resources/org/prebid/server/it/openrtb2/sharethrough/test-sharethrough-bid-request.json
Labels: do not port

#3590 Amp: update consented providers settings support
  src/main/java/org/prebid/server/auction/requestfactory/AmpRequestFactory.java
  src/main/java/org/prebid/server/proto/openrtb/ext/request/ExtUser.java
  src/test/java/org/prebid/server/auction/requestfactory/AmpRequestFactoryTest.java
  src/test/java/org/prebid/server/bidder/improvedigital/ImprovedigitalBidderTest.java
  src/test/resources/org/prebid/server/it/amp/test-generic-bid-request.json
  src/test/resources/org/prebid/server/it/amp/test-genericAlias-bid-request.json
Labels: do not port

#3559 Increase test coverage for GDPR enforcement when COPPA in scope
  src/test/groovy/org/prebid/server/functional/model/request/auction/PublicCountryIp.groovy
  src/test/groovy/org/prebid/server/functional/model/request/auction/RegsExt.groovy
  src/test/groovy/org/prebid/server/functional/tests/privacy/GdprAmpSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/privacy/GdprAuctionSpec.groovy
Labels: tests

#3577 Test: `consented_providers_settings`
  src/test/groovy/org/prebid/server/functional/model/request/auction/ConsentedProvidersSettings.groovy
  src/test/groovy/org/prebid/server/functional/model/request/auction/UserExt.groovy
  src/test/groovy/org/prebid/server/functional/tests/AmpSpec.groovy
Labels: tests

#3595 Add functional tests for module-execution host level config
  src/test/groovy/org/prebid/server/functional/testcontainers/container/PrebidServerContainer.groovy
  src/test/groovy/org/prebid/server/functional/tests/module/GeneralModuleSpec.groovy
Labels: tests

#3591 Add missing server config properties for config-app.md file
  docs/config-app.md
Labels: do not port

#3598 Docs: PBS sample
  sample/configs/prebid-config-with-51d-dd.yaml
  sample/configs/prebid-config-with-module.yaml
Labels: do not port

#3597 Bids Rejection Refactoring
  extra/modules/ortb2-blocking/src/main/java/org/prebid/server/hooks/modules/ortb2/blocking/core/BidsBlocker.java
  extra/modules/ortb2-blocking/src/test/java/org/prebid/server/hooks/modules/ortb2/blocking/core/BidsBlockerTest.java
  extra/modules/pb-richmedia-filter/src/main/java/org/prebid/server/hooks/modules/pb/richmedia/filter/core/BidResponsesMraidFilter.java
  extra/modules/pb-richmedia-filter/src/test/java/org/prebid/server/hooks/modules/pb/richmedia/filter/core/BidResponsesMraidFilterTest.java
  src/main/java/org/prebid/server/analytics/reporter/greenbids/GreenbidsAnalyticsReporter.java
  src/main/java/org/prebid/server/auction/BidResponseCreator.java
  src/main/java/org/prebid/server/auction/DsaEnforcer.java
  src/main/java/org/prebid/server/auction/ExchangeService.java
  src/main/java/org/prebid/server/auction/model/BidRejectionReason.java
  src/main/java/org/prebid/server/auction/model/BidRejectionTracker.java
  src/main/java/org/prebid/server/bidder/HttpBidderRequester.java
  src/main/java/org/prebid/server/floors/BasicPriceFloorEnforcer.java
  src/main/java/org/prebid/server/validation/ResponseBidValidator.java
  src/test/groovy/org/prebid/server/functional/model/response/auction/BidRejectionReason.groovy
  src/test/groovy/org/prebid/server/functional/tests/SeatNonBidSpec.groovy
  src/test/java/org/prebid/server/analytics/reporter/greenbids/GreenbidsAnalyticsReporterTest.java
  src/test/java/org/prebid/server/auction/BidResponseCreatorTest.java
  src/test/java/org/prebid/server/auction/DsaEnforcerTest.java
  src/test/java/org/prebid/server/auction/ExchangeServiceTest.java
  src/test/java/org/prebid/server/auction/model/BidRejectionTrackerTest.java
  src/test/java/org/prebid/server/bidder/HttpBidderRequesterTest.java
  src/test/java/org/prebid/server/floors/BasicPriceFloorEnforcerTest.java
  src/test/java/org/prebid/server/validation/ResponseBidValidatorTest.java
Labels: do not port

#3624 GreenBids module: Ignore broken tests
  extra/modules/greenbids-real-time-data/src/test/java/org/prebid/server/hooks/modules/greenbids/real/time/data/v1/GreenbidsRealTimeDataProcessedAuctionRequestHookTest.java
Labels: tests, do not port

#3616 Conversant: Enable audio requests #3605
  src/main/java/org/prebid/server/bidder/epsilon/EpsilonBidder.java
  src/main/resources/bidder-config/epsilon.yaml
  src/test/java/org/prebid/server/bidder/epsilon/EpsilonBidderTest.java
Labels: do not port

#3617 update functional test for module execution
  src/test/groovy/org/prebid/server/functional/tests/module/GeneralModuleSpec.groovy
Labels: tests

#3623 Fix #3581 declare PubMatic support for openRTB 2.6
  src/main/resources/bidder-config/pubmatic.yaml
  src/test/resources/org/prebid/server/it/openrtb2/pubmatic/test-auction-pubmatic-request.json
  src/test/resources/org/prebid/server/it/openrtb2/pubmatic/test-pubmatic-bid-request.json
Labels: do not port

#3599 Tests: Add adUnitCode to exception list
  src/test/groovy/org/prebid/server/functional/model/request/auction/ImpExtPrebid.groovy
  src/test/groovy/org/prebid/server/functional/model/request/auction/Prebid.groovy
  src/test/groovy/org/prebid/server/functional/tests/BidderParamsSpec.groovy
Labels: tests

#3638 Create slack-stale-pr.yml
  .github/workflows/slack-stale-pr.yml
Labels: do not port

#3640 Docs: Fix incorrect Java version reference in the build.md
  docs/build.md
Labels: do not port

#3641 PgamSSP adapter : add GVL ID
  src/main/resources/bidder-config/pgamssp.yaml
Labels: do not port

#3644 Update privacy functional test: GVL file handling
  src/test/groovy/org/prebid/server/functional/tests/privacy/ActivityTraceLogSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/privacy/GdprAmpSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/privacy/GdprAuctionSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/privacy/GppSyncUserActivitiesSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/privacy/PrivacyBaseSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/privacy/TcfFullTransmitEidsActivitiesSpec.groovy
Labels: tests, do not port
