Repository prebid/prebid-server-java, pull requests merged in 2024-08, with the labels that each got.

#3335 Triplelift Native Bidder Update
  src/main/java/org/prebid/server/bidder/tripleliftnative/TripleliftNativeBidder.java
  src/main/java/org/prebid/server/bidder/tripleliftnative/TripleliftNativeExtImp.java
  src/main/java/org/prebid/server/bidder/tripleliftnative/TripleliftNativeExtImpData.java
  src/main/resources/bidder-config/tripleliftnative.yaml
  src/main/resources/static/bidder-params/triplelift_native.json
  src/test/java/org/prebid/server/bidder/tripleliftnative/TripleliftNativeBidderTest.java
Labels: do not port

#3346 Add functional tests for bidder specific imp-level parameters
  src/test/groovy/org/prebid/server/functional/model/bidder/BidderName.groovy
  src/test/groovy/org/prebid/server/functional/model/bidderspecific/BidderImp.groovy
  src/test/groovy/org/prebid/server/functional/model/request/auction/Deal.groovy
  src/test/groovy/org/prebid/server/functional/model/request/auction/DealExt.groovy
  src/test/groovy/org/prebid/server/functional/model/request/auction/DealLineItem.groovy
  src/test/groovy/org/prebid/server/functional/model/request/auction/Format.groovy
  src/test/groovy/org/prebid/server/functional/model/request/auction/ImpExtPrebid.groovy
  src/test/groovy/org/prebid/server/functional/model/request/auction/Pmp.groovy
  src/test/groovy/org/prebid/server/functional/tests/BidderFormatSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/ImpRequestSpec.groovy
Labels: tests

#3345 Unruly: Add duration to video bids
  src/main/java/org/prebid/server/bidder/unruly/UnrulyBidder.java
  src/main/java/org/prebid/server/proto/openrtb/ext/response/ExtBidPrebidVideo.java
  src/test/java/org/prebid/server/bidder/unruly/UnrulyBidderTest.java
Labels: do not port

#3350 AMX: Demand Source and aDomain support
  src/main/java/org/prebid/server/bidder/amx/AmxBidder.java
  src/main/java/org/prebid/server/bidder/amx/model/AmxBidExt.java
  src/test/java/org/prebid/server/bidder/amx/AmxBidderTest.java
Labels: do not port

#3354 Tests: Fix flaky floors test
  src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsEnforcementSpec.groovy
Labels: tests, do not port

#3344 Criteo Bidder: Support Fledge
  src/main/java/org/prebid/server/bidder/criteo/CriteoBidResponse.java
  src/main/java/org/prebid/server/bidder/criteo/CriteoBidder.java
  src/main/java/org/prebid/server/bidder/criteo/CriteoExtBidResponse.java
  src/main/java/org/prebid/server/bidder/criteo/CriteoIgiExtBidResponse.java
  src/main/java/org/prebid/server/bidder/criteo/CriteoIgsIgiExtBidResponse.java
  src/test/java/org/prebid/server/bidder/criteo/CriteoBidderTest.java
Labels: do not port

#3355 QT: Add adapter
  src/main/java/org/prebid/server/bidder/qt/QtBidder.java
  src/main/java/org/prebid/server/bidder/qt/proto/QtImpExtBidder.java
  src/main/java/org/prebid/server/proto/openrtb/ext/request/ExtImpQt.java
  src/main/java/org/prebid/server/spring/config/bidder/QtConfiguration.java
  src/main/resources/bidder-config/qt.yaml
  src/main/resources/static/bidder-params/qt.json
  src/test/java/org/prebid/server/bidder/qt/QtBidderTest.java
  src/test/java/org/prebid/server/bidder/vidazoo/VidazooBidderTest.java
  src/test/java/org/prebid/server/it/QtTest.java
  src/test/resources/org/prebid/server/it/openrtb2/qt/test-auction-qt-request.json
  src/test/resources/org/prebid/server/it/openrtb2/qt/test-auction-qt-response.json
  src/test/resources/org/prebid/server/it/openrtb2/qt/test-qt-bid-request.json
  src/test/resources/org/prebid/server/it/openrtb2/qt/test-qt-bid-response.json
  src/test/resources/org/prebid/server/it/test-application.properties
Labels: do not port

#3362 Increase test coverage for naming and alias cases in bidderControls
  src/test/groovy/org/prebid/server/functional/model/request/auction/BidderControls.groovy
  src/test/groovy/org/prebid/server/functional/tests/FilterMultiFormatSpec.groovy
Labels: tests

#3369 Price Floors Test Fix
  src/test/java/org/prebid/server/it/PriceFloorsTest.java
Labels: do not port

#3368 Playdigo Bidder: Usersync Support
  src/main/resources/bidder-config/playdigo.yaml
Labels: do not port

#3254 Support Bidder Specific Imp Level Params
  src/main/java/org/prebid/server/auction/ExchangeService.java
  src/main/java/org/prebid/server/auction/ImpAdjuster.java
  src/main/java/org/prebid/server/proto/openrtb/ext/request/ExtImpPrebid.java
  src/main/java/org/prebid/server/spring/config/ServiceConfiguration.java
  src/main/java/org/prebid/server/validation/ImpValidator.java
  src/main/java/org/prebid/server/validation/RequestValidator.java
  src/main/java/org/prebid/server/validation/ValidationException.java
  src/test/groovy/org/prebid/server/functional/model/bidder/BidderName.groovy
  src/test/groovy/org/prebid/server/functional/model/bidderspecific/BidderImp.groovy
  src/test/groovy/org/prebid/server/functional/model/request/auction/Deal.groovy
  src/test/groovy/org/prebid/server/functional/model/request/auction/DealExt.groovy
  src/test/groovy/org/prebid/server/functional/model/request/auction/DealLineItem.groovy
  src/test/groovy/org/prebid/server/functional/model/request/auction/Format.groovy
  src/test/groovy/org/prebid/server/functional/model/request/auction/ImpExtPrebid.groovy
  src/test/groovy/org/prebid/server/functional/model/request/auction/Pmp.groovy
  src/test/groovy/org/prebid/server/functional/tests/BidderFormatSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/ImpRequestSpec.groovy
  src/test/java/org/prebid/server/auction/ExchangeServiceTest.java
  src/test/java/org/prebid/server/auction/ImpAdjusterTest.java
  src/test/java/org/prebid/server/validation/ImpValidatorTest.java
  src/test/java/org/prebid/server/validation/RequestValidatorTest.java
  src/test/resources/org/prebid/server/it/openrtb2/generic_core_functionality/test-auction-generic-request.json
  src/test/resources/org/prebid/server/it/openrtb2/generic_core_functionality/test-generic-bid-request.json
Labels: do not port

#2868 Core: Add new `OwnAdx` bidder
  src/main/java/org/prebid/server/bidder/ownadx/OwnAdxBidder.java
  src/main/java/org/prebid/server/proto/openrtb/ext/request/ownadx/ExtImpOwnAdx.java
  src/main/java/org/prebid/server/spring/config/bidder/OwnAdxBidderConfiguration.java
  src/main/resources/bidder-config/ownadx.yaml
  src/main/resources/static/bidder-params/ownadx.json
  src/test/java/org/prebid/server/bidder/ownadx/OwnAdxBidderTest.java
  src/test/java/org/prebid/server/it/OwnAdxTest.java
  src/test/resources/org/prebid/server/it/openrtb2/ownadx/test-auction-ownadx-request.json
  src/test/resources/org/prebid/server/it/openrtb2/ownadx/test-auction-ownadx-response.json
  src/test/resources/org/prebid/server/it/openrtb2/ownadx/test-ownadx-bid-request.json
  src/test/resources/org/prebid/server/it/openrtb2/ownadx/test-ownadx-bid-response.json
  src/test/resources/org/prebid/server/it/test-application.properties
Labels: do not port

#3370 The Trade Desk Bidder
  src/main/java/org/prebid/server/bidder/thetradedesk/TheTradeDeskBidder.java
  src/main/java/org/prebid/server/proto/openrtb/ext/request/thetradedesk/ExtImpTheTradeDesk.java
  src/main/java/org/prebid/server/spring/config/bidder/TheTradeDeskConfiguration.java
  src/main/resources/bidder-config/thetradedesk.yaml
  src/main/resources/static/bidder-params/thetradedesk.json
  src/test/java/org/prebid/server/bidder/thetradedesk/TheTradeDeskBidderTest.java
  src/test/java/org/prebid/server/it/TheTradeDeskTest.java
  src/test/resources/org/prebid/server/it/openrtb2/thetradedesk/test-auction-thetradedesk-request.json
  src/test/resources/org/prebid/server/it/openrtb2/thetradedesk/test-auction-thetradedesk-response.json
  src/test/resources/org/prebid/server/it/openrtb2/thetradedesk/test-thetradedesk-bid-request.json
  src/test/resources/org/prebid/server/it/openrtb2/thetradedesk/test-thetradedesk-bid-response.json
  src/test/resources/org/prebid/server/it/test-application.properties
Labels: do not port

#3383 Rename Liftoff to Vungle
  src/main/java/org/prebid/server/bidder/liftoff/model/LiftoffImpressionExt.java
  src/main/java/org/prebid/server/bidder/vungle/VungleBidder.java
  src/main/java/org/prebid/server/bidder/vungle/model/VungleImpressionExt.java
  src/main/java/org/prebid/server/proto/openrtb/ext/request/vungle/ExtImpVungle.java
  src/main/java/org/prebid/server/spring/config/bidder/VungleConfiguration.java
  src/main/resources/bidder-config/vungle.yaml
  src/main/resources/static/bidder-params/vungle.json
  src/test/java/org/prebid/server/bidder/vungle/VungleBidderTest.java
  src/test/java/org/prebid/server/it/LiftoffTest.java
  src/test/java/org/prebid/server/it/VungleTest.java
  src/test/resources/org/prebid/server/it/openrtb2/vungle/test-auction-vungle-request.json
  src/test/resources/org/prebid/server/it/openrtb2/vungle/test-auction-vungle-response.json
  src/test/resources/org/prebid/server/it/openrtb2/vungle/test-vungle-bid-request.json
  src/test/resources/org/prebid/server/it/openrtb2/vungle/test-vungle-bid-response.json
  src/test/resources/org/prebid/server/it/test-application.properties
Labels: do not port

#3378 Remove all imp.ext.prebid.imp
  src/main/java/org/prebid/server/auction/ImpAdjuster.java
  src/test/groovy/org/prebid/server/functional/tests/ImpRequestSpec.groovy
  src/test/java/org/prebid/server/auction/ImpAdjusterTest.java
Labels: do not port

#3397 Add a functional test to ensure that bidder implementation is always merged
  src/test/groovy/org/prebid/server/functional/tests/ImpRequestSpec.groovy
Labels: tests

#3401 Adnuntius: Use format=prebid on adserver requests
  src/main/java/org/prebid/server/bidder/adnuntius/AdnuntiusBidder.java
  src/test/java/org/prebid/server/bidder/adnuntius/AdnuntiusBidderTest.java
Labels: do not port

#3403 Smarthub: New aliasses (`VimayX`, `FelixAds`)
  src/main/resources/bidder-config/smarthub.yaml
  src/test/java/org/prebid/server/it/FelixadsTest.java
  src/test/java/org/prebid/server/it/VimayxTest.java
  src/test/resources/org/prebid/server/it/openrtb2/felixads/test-auction-felixads-request.json
  src/test/resources/org/prebid/server/it/openrtb2/felixads/test-auction-felixads-response.json
  src/test/resources/org/prebid/server/it/openrtb2/felixads/test-felixads-bid-request.json
  src/test/resources/org/prebid/server/it/openrtb2/felixads/test-felixads-bid-response.json
  src/test/resources/org/prebid/server/it/openrtb2/vimayx/test-auction-vimayx-request.json
  src/test/resources/org/prebid/server/it/openrtb2/vimayx/test-auction-vimayx-response.json
  src/test/resources/org/prebid/server/it/openrtb2/vimayx/test-vimayx-bid-request.json
  src/test/resources/org/prebid/server/it/openrtb2/vimayx/test-vimayx-bid-response.json
  src/test/resources/org/prebid/server/it/test-application.properties
Labels: do not port

#3402 Consumable: Endpoint update
  src/main/resources/bidder-config/consumable.yaml
Labels: do not port

#3406 Bidders Ortb Version Update
  src/main/resources/bidder-config/freewheelssp.yaml
  src/main/resources/bidder-config/kargo.yaml
  src/main/resources/bidder-config/mobilefuse.yaml
  src/main/resources/bidder-config/pulsepoint.yaml
  src/main/resources/bidder-config/vidazoo.yaml
  src/test/resources/org/prebid/server/it/openrtb2/freewheelssp/test-freewheelssp-bid-request.json
  src/test/resources/org/prebid/server/it/openrtb2/kargo/test-kargo-bid-request.json
  src/test/resources/org/prebid/server/it/openrtb2/mobilefuse/test-mobilefuse-bid-request.json
  src/test/resources/org/prebid/server/it/openrtb2/pulsepoint/test-pulsepoint-bid-request-params-as-string.json
  src/test/resources/org/prebid/server/it/openrtb2/pulsepoint/test-pulsepoint-bid-request.json
Labels: do not port

#3396 Fix merging imp.ext.prebid.imp into imp
  src/main/java/org/prebid/server/auction/ExchangeService.java
  src/test/groovy/org/prebid/server/functional/tests/ImpRequestSpec.groovy
  src/test/java/org/prebid/server/auction/ExchangeServiceTest.java
Labels: do not port

#3407 Taboola Bidder: App Support
  src/main/java/org/prebid/server/bidder/taboola/TaboolaBidder.java
  src/test/java/org/prebid/server/bidder/taboola/TaboolaBidderTest.java
Labels: do not port

#3385 Fix bug caused by incorrect usage of Promise
  src/main/java/org/prebid/server/vertx/verticles/server/DaemonVerticle.java
Labels: bug, do not port

#3387 Adtarget and Adtelligent Bidders: Change Aid Type
  src/main/java/org/prebid/server/bidder/adtarget/AdtargetBidder.java
  src/main/java/org/prebid/server/bidder/adtarget/proto/AdtargetImpExt.java
  src/main/java/org/prebid/server/bidder/adtarget/proto/ExtImpAdtargetBidRequest.java
  src/main/java/org/prebid/server/bidder/adtelligent/AdtelligentBidder.java
  src/main/java/org/prebid/server/bidder/adtelligent/proto/AdtelligentImpExt.java
  src/main/java/org/prebid/server/bidder/adtelligent/proto/ExtImpAdtelligentBidRequest.java
  src/main/java/org/prebid/server/proto/openrtb/ext/request/adtarget/ExtImpAdtarget.java
  src/main/java/org/prebid/server/proto/openrtb/ext/request/adtelligent/ExtImpAdtelligent.java
  src/main/resources/static/bidder-params/adtelligent.json
  src/test/java/org/prebid/server/bidder/adtarget/AdtargetBidderTest.java
  src/test/java/org/prebid/server/bidder/adtelligent/AdtelligentBidderTest.java
  src/test/java/org/prebid/server/validation/BidderParamValidatorTest.java
Labels: do not port
