Repository prebid/prebid-server-java, pull requests merged in 2024-01, with the labels that each got.

#2870 Core: Add new `Xtrmqb` bidder
  src/main/resources/bidder-config/limelightDigital.yaml
  src/test/java/org/prebid/server/it/XtrmqbGameTest.java
  src/test/resources/org/prebid/server/it/openrtb2/xtrmqb/test-auction-xtrmqb-request.json
  src/test/resources/org/prebid/server/it/openrtb2/xtrmqb/test-auction-xtrmqb-response.json
  src/test/resources/org/prebid/server/it/openrtb2/xtrmqb/test-xtrmqb-bid-request.json
  src/test/resources/org/prebid/server/it/openrtb2/xtrmqb/test-xtrmqb-bid-response.json
  src/test/resources/org/prebid/server/it/test-application.properties
Labels: do not port

#2871 SaLunamedia: Update params
  src/main/resources/static/bidder-params/sa_lunamedia.json
  src/test/resources/org/prebid/server/it/openrtb2/salunamedia/test-auction-salunamedia-request.json
  src/test/resources/org/prebid/server/it/openrtb2/salunamedia/test-salunamedia-bid-request.json
Labels: do not port

#2872 Adsinteractive: change usersync endpoint to https
  src/main/resources/bidder-config/generic.yaml
Labels: do not port

#2873 Axis: Updated url
  src/main/java/org/prebid/server/bidder/axis/AxisBidder.java
  src/main/resources/bidder-config/axis.yaml
  src/test/java/org/prebid/server/bidder/axis/AxisBidderTest.java
  src/test/java/org/prebid/server/it/AxisTest.java
  src/test/resources/org/prebid/server/it/test-application.properties
Labels: do not port

#2874 Adsinteractive: Usersync updates + gvlVendorID
  src/main/resources/bidder-config/generic.yaml
Labels: do not port

#2570 Tests: Increase test coverage for `cookie_sync`
  src/test/groovy/org/prebid/server/functional/model/bidder/BidderName.groovy
  src/test/groovy/org/prebid/server/functional/model/mock/services/vendorlist/VendorListResponse.groovy
  src/test/groovy/org/prebid/server/functional/model/request/cookiesync/MethodFilter.groovy
  src/test/groovy/org/prebid/server/functional/model/response/setuid/SetuidResponse.groovy
  src/test/groovy/org/prebid/server/functional/service/PrebidServerService.groovy
  src/test/groovy/org/prebid/server/functional/testcontainers/scaffolding/VendorList.groovy
  src/test/groovy/org/prebid/server/functional/tests/BaseSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/CookieSyncSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/CurrencySpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/SetUidSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/SmokeSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsSignalingSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/privacy/GdprAmpSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/privacy/GdprAuctionSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/privacy/GppAuctionSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/privacy/GppCookieSyncSpec.groovy
  src/test/groovy/org/prebid/server/functional/util/privacy/TcfConsent.groovy
Labels: tests

#2855 Liftoff Site Support
  src/main/java/org/prebid/server/bidder/liftoff/LiftoffBidder.java
  src/main/resources/bidder-config/liftoff.yaml
  src/test/java/org/prebid/server/bidder/liftoff/LiftoffBidderTest.java
  src/test/resources/org/prebid/server/it/openrtb2/liftoff/test-auction-liftoff-request.json
  src/test/resources/org/prebid/server/it/openrtb2/liftoff/test-liftoff-bid-request.json
Labels: do not port

#2882 Bliink: Iframe added to usersync
  src/main/resources/bidder-config/bliink.yaml
Labels: do not port

#2883 Update teads contact info
  src/main/resources/bidder-config/teads.yaml
Labels: do not port

#2886 BMTM: App support
  src/main/resources/bidder-config/bmtm.yaml
Labels: do not port

#2885 Embimedia: New Adapter
  src/main/resources/bidder-config/limelightDigital.yaml
  src/test/java/org/prebid/server/it/EmbimediaTest.java
  src/test/java/org/prebid/server/it/XtrmqbTest.java
  src/test/resources/org/prebid/server/it/openrtb2/embimedia/test-auction-embimedia-request.json
  src/test/resources/org/prebid/server/it/openrtb2/embimedia/test-auction-embimedia-response.json
  src/test/resources/org/prebid/server/it/openrtb2/embimedia/test-embimedia-bid-request.json
  src/test/resources/org/prebid/server/it/openrtb2/embimedia/test-embimedia-bid-response.json
  src/test/resources/org/prebid/server/it/test-application.properties
Labels: do not port

#2888 Oms: Add adapter
  src/main/java/org/prebid/server/bidder/oms/OmsBidder.java
  src/main/java/org/prebid/server/spring/config/bidder/OmsBidderConfiguration.java
  src/main/resources/bidder-config/oms.yaml
  src/main/resources/static/bidder-params/oms.json
  src/test/java/org/prebid/server/bidder/oms/OmsBidderTest.java
  src/test/java/org/prebid/server/it/OmsTest.java
  src/test/resources/org/prebid/server/it/openrtb2/oms/test-auction-oms-request.json
  src/test/resources/org/prebid/server/it/openrtb2/oms/test-auction-oms-response.json
  src/test/resources/org/prebid/server/it/openrtb2/oms/test-oms-bid-request.json
  src/test/resources/org/prebid/server/it/openrtb2/oms/test-oms-bid-response.json
  src/test/resources/org/prebid/server/it/test-application.properties
Labels: do not port

#2863 Add additional checks for only remove the transaction id from source obj if not present
  src/test/groovy/org/prebid/server/functional/tests/privacy/GppTransmitTidActivitiesSpec.groovy
Labels: tests

#2889 Tests: Fix for currency spec
  src/test/groovy/org/prebid/server/functional/tests/CurrencySpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsCurrencySpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/privacy/PrivacyBaseSpec.groovy
Labels: tests

#2881 Add additional tests case for `cookie sync spec`
  src/test/groovy/org/prebid/server/functional/tests/CookieSyncSpec.groovy
Labels: tests

#2838 Test: Increase tests logic for targeting prefix
  src/test/groovy/org/prebid/server/functional/model/response/auction/ErrorType.groovy
  src/test/groovy/org/prebid/server/functional/tests/TargetingSpec.groovy
Labels: tests

#2906 Tests: Add fix for `multibidspec` flaky tests
  src/test/groovy/org/prebid/server/functional/tests/MultibidSpec.groovy
Labels: tests, do not port

#2908 Tests: Generalize names of some test entities
  src/test/groovy/org/prebid/server/functional/model/deals/lineitem/targeting/TargetingType.groovy
  src/test/groovy/org/prebid/server/functional/model/request/auction/GeoExt.groovy
  src/test/groovy/org/prebid/server/functional/model/request/auction/GeoExtGeoProvider.groovy
  src/test/groovy/org/prebid/server/functional/tests/pg/TargetingSpec.groovy
  src/test/java/org/prebid/server/deals/TargetingServiceTest.java
  src/test/resources/org/prebid/server/deals/targeting/test-device-targeting.json
Labels: tests, do not port

#2891 MType Support for the Adxcg Bidder
  src/main/java/org/prebid/server/bidder/adxcg/AdxcgBidder.java
  src/test/java/org/prebid/server/bidder/adxcg/AdxcgBidderTest.java
  src/test/resources/org/prebid/server/it/openrtb2/adxcg/test-adxcg-bid-response.json
  src/test/resources/org/prebid/server/it/openrtb2/adxcg/test-auction-adxcg-response.json
Labels: do not port

#2904 Add `GppModelWrapper`.
  src/main/java/org/prebid/server/auction/gpp/model/GppContextUtils.java
  src/main/java/org/prebid/server/auction/gpp/model/GppModelWrapper.java
  src/test/java/org/prebid/server/auction/gpp/model/GppModelWrapperTest.java
Labels: do not port

#2896 Add Cadent Aperture Mx Alias
  src/main/resources/bidder-config/emxdigital.yaml
  src/test/java/org/prebid/server/it/ApplicationTest.java
  src/test/java/org/prebid/server/it/CadentApertureMxTest.java
  src/test/resources/org/prebid/server/it/openrtb2/cadentaperturemx/test-auction-cadentaperturemx-request.json
  src/test/resources/org/prebid/server/it/openrtb2/cadentaperturemx/test-auction-cadentaperturemx-response.json
  src/test/resources/org/prebid/server/it/openrtb2/cadentaperturemx/test-cadentaperturemx-bid-request.json
  src/test/resources/org/prebid/server/it/openrtb2/cadentaperturemx/test-cadentaperturemx-bid-response.json
  src/test/resources/org/prebid/server/it/test-application.properties
Labels: do not port

#2902 Add Bematterfull Adapter
  src/main/java/org/prebid/server/bidder/bematterfull/BematterfullBidder.java
  src/main/java/org/prebid/server/proto/openrtb/ext/request/bematterfull/ExtImpBematterfull.java
  src/main/java/org/prebid/server/spring/config/bidder/BematterfullConfiguration.java
  src/main/resources/bidder-config/bematterfull.yaml
  src/main/resources/static/bidder-params/bematterfull.json
  src/test/java/org/prebid/server/bidder/bematterfull/BematterfullBidderTest.java
  src/test/java/org/prebid/server/it/BematterfullTest.java
  src/test/resources/org/prebid/server/it/openrtb2/bematterfull/test-auction-bematterfull-request.json
  src/test/resources/org/prebid/server/it/openrtb2/bematterfull/test-auction-bematterfull-response.json
  src/test/resources/org/prebid/server/it/openrtb2/bematterfull/test-bematterfull-bid-request.json
  src/test/resources/org/prebid/server/it/openrtb2/bematterfull/test-bematterfull-bid-response.json
  src/test/resources/org/prebid/server/it/test-application.properties
Labels: do not port

#2903 Core: Add new `LemmaDigital` bidder
  src/main/java/org/prebid/server/bidder/lemmadigital/LemmaDigitalBidder.java
  src/main/java/org/prebid/server/proto/openrtb/ext/request/lemmadigital/ExtImpLemmaDigital.java
  src/main/java/org/prebid/server/spring/config/bidder/LemmaDigitalConfiguration.java
  src/main/resources/bidder-config/lemmadigital.yaml
  src/main/resources/static/bidder-params/lemmadigital.json
  src/test/java/org/prebid/server/bidder/lemmadigital/LemmaDigitalBidderTest.java
  src/test/java/org/prebid/server/it/LemmaDigitalTest.java
  src/test/resources/org/prebid/server/it/openrtb2/lemmaDigital/test-auction-lemmaDigital-request.json
  src/test/resources/org/prebid/server/it/openrtb2/lemmaDigital/test-auction-lemmaDigital-response.json
  src/test/resources/org/prebid/server/it/openrtb2/lemmaDigital/test-lemmaDigital-bid-request.json
  src/test/resources/org/prebid/server/it/openrtb2/lemmaDigital/test-lemmaDigital-bid-response.json
  src/test/resources/org/prebid/server/it/test-application.properties
Labels: do not port

#2884 GitHub action: Docker image build and publish
  .github/workflows/docker-image-publish.yml
  README.md
Labels: do not port

#2843 GitHub action: release assets build and publish
  .github/workflows/release-asset-publish.yml
  README.md
Labels: do not port

#2910 NextMillennium: Add `extraInfo` support and update `yaml`
  src/main/java/org/prebid/server/bidder/nextmillennium/NextMillenniumBidder.java
  src/main/java/org/prebid/server/spring/config/bidder/NextMillenniumConfiguration.java
  src/main/resources/bidder-config/nextmillennium.yaml
  src/test/java/org/prebid/server/bidder/nextmillennium/NextMillenniumBidderTest.java
  src/test/resources/org/prebid/server/it/openrtb2/nextmillennium/test-nextmillennium-bid-request.json
  src/test/resources/org/prebid/server/it/test-application.properties
Labels: do not port

#2915 Add Relevant Digital Adapter
  src/main/java/org/prebid/server/bidder/relevantdigital/RelevantDigitalBidder.java
  src/main/java/org/prebid/server/proto/openrtb/ext/request/relevantdigital/ExtImpRelevantDigital.java
  src/main/java/org/prebid/server/spring/config/bidder/RelevantDigitalConfiguration.java
  src/main/resources/bidder-config/relevantdigital.yaml
  src/main/resources/static/bidder-params/relevantdigital.json
  src/test/java/org/prebid/server/bidder/relevantdigital/RelevantDigitalBidderTest.java
  src/test/java/org/prebid/server/it/RelevantDigitalTest.java
  src/test/resources/org/prebid/server/it/openrtb2/relevantdigital/test-auction-relevantdigital-request.json
  src/test/resources/org/prebid/server/it/openrtb2/relevantdigital/test-auction-relevantdigital-response.json
  src/test/resources/org/prebid/server/it/openrtb2/relevantdigital/test-relevantdigital-bid-request.json
  src/test/resources/org/prebid/server/it/openrtb2/relevantdigital/test-relevantdigital-bid-response.json
  src/test/resources/org/prebid/server/it/test-application.properties
Labels: do not port

#2929 Synchronise dependencies between PBS and PBS-bundle
  extra/bundle/pom.xml
  extra/modules/confiant-ad-quality/pom.xml
  extra/modules/ortb2-blocking/pom.xml
  extra/modules/pb-richmedia-filter/pom.xml
  extra/modules/pom.xml
  extra/pom.xml
  pom.xml
Labels: dependencies, do not port
