Repository prebid/prebid-server-java, pull requests merged in 2024-03, with the labels that each got.

#3024 Workflows: Add trivy dependency scanner
  .github/workflows/pr-functional-tests.yml
  .github/workflows/pr-java-ci.yml
  .github/workflows/pr-module-functional-tests.yml
  .github/workflows/release-asset-publish.yml
  .github/workflows/trivy-security-check.yml
  pom.xml
Labels: do not port, PBS 3.0

#3019 MinuteMedia: Add new bidder
  src/main/java/org/prebid/server/bidder/minutemedia/MinuteMediaBidder.java
  src/main/java/org/prebid/server/proto/openrtb/ext/request/minutemedia/ExtImpMinuteMedia.java
  src/main/java/org/prebid/server/spring/config/bidder/MinuteMediaConfiguration.java
  src/main/resources/bidder-config/minutemedia.yaml
  src/main/resources/static/bidder-params/minutemedia.json
  src/test/java/org/prebid/server/bidder/minutemedia/MinuteMediaBidderTest.java
  src/test/java/org/prebid/server/it/MinuteMediaTest.java
  src/test/resources/org/prebid/server/it/openrtb2/minutemedia/test-auction-minutemedia-request.json
  src/test/resources/org/prebid/server/it/openrtb2/minutemedia/test-auction-minutemedia-response.json
  src/test/resources/org/prebid/server/it/openrtb2/minutemedia/test-minutemedia-bid-request.json
  src/test/resources/org/prebid/server/it/openrtb2/minutemedia/test-minutemedia-bid-response.json
  src/test/resources/org/prebid/server/it/test-application.properties
Labels: do not port

#3062 Test: geo lookup
  src/test/groovy/org/prebid/server/functional/model/config/AccountConfig.groovy
  src/test/groovy/org/prebid/server/functional/model/config/AccountSetting.groovy
  src/test/groovy/org/prebid/server/functional/model/pricefloors/Country.groovy
  src/test/groovy/org/prebid/server/functional/model/request/auction/PublicCountryIp.groovy
  src/test/groovy/org/prebid/server/functional/tests/GeoSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/privacy/ActivityTraceLogSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/privacy/GppFetchBidActivitiesSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/privacy/GppSyncUserActivitiesSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/privacy/GppTransmitEidsActivitiesSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/privacy/GppTransmitPreciseGeoActivitiesSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/privacy/GppTransmitUfpdActivitiesSpec.groovy
Labels: tests

#3070 Tests: increase coverage for `/vtrack`
  src/test/groovy/org/prebid/server/functional/tests/CacheSpec.groovy
Labels: tests

#3043 Test: Remove flaky timeout tests
  src/test/groovy/org/prebid/server/functional/tests/TimeoutSpec.groovy
Labels: tests

#3058 Docs: Documentation for transmitEids
  docs/application-settings.md
Labels: do not port

#3044 Iqzone: Add mType support
  src/main/java/org/prebid/server/bidder/iqzone/IqzoneBidder.java
  src/test/java/org/prebid/server/bidder/iqzone/IqzoneBidderTest.java
  src/test/resources/org/prebid/server/it/openrtb2/iqzone/test-auction-iqzone-response.json
  src/test/resources/org/prebid/server/it/openrtb2/iqzone/test-iqzone-bid-response.json
Labels: do not port

#2962 Bizzclick: host parameter update
  src/main/java/org/prebid/server/bidder/bizzclick/BizzclickBidder.java
  src/main/java/org/prebid/server/proto/openrtb/ext/request/bizzclick/ExtImpBizzclick.java
  src/main/resources/bidder-config/bizzclick.yaml
  src/test/java/org/prebid/server/bidder/bizzclick/BizzclickBidderTest.java
  src/test/java/org/prebid/server/it/BizzclickTest.java
  src/test/resources/org/prebid/server/it/openrtb2/bizzclick/test-auction-bizzclick-request.json
  src/test/resources/org/prebid/server/it/test-application.properties
Labels: do not port

#3042 MediaGrid: Add GPP Macros
  src/main/resources/bidder-config/grid.yaml
Labels: do not port

#3023 RTB House: regional endpoints
  src/main/resources/bidder-config/rtbhouse.yaml
Labels: do not port

#2970 Test: Add tests for exponential backoff
  src/test/groovy/org/prebid/server/functional/testcontainers/scaffolding/VendorList.groovy
  src/test/groovy/org/prebid/server/functional/tests/privacy/GdprAmpSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/privacy/GdprAuctionSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/privacy/PrivacyBaseSpec.groovy
Labels: tests

#3051 Adnuntius: add ability to fetch data from site.ext
  src/main/java/org/prebid/server/bidder/adnuntius/AdnuntiusBidder.java
  src/main/java/org/prebid/server/bidder/adnuntius/model/request/AdnuntiusMetaData.java
  src/main/java/org/prebid/server/bidder/adnuntius/model/request/AdnuntiusRequest.java
  src/main/java/org/prebid/server/bidder/adnuntius/model/response/AdnuntiusAd.java
  src/main/java/org/prebid/server/bidder/adnuntius/model/util/AdsUnitWithImpId.java
  src/test/java/org/prebid/server/bidder/adnuntius/AdnuntiusBidderTest.java
  src/test/resources/org/prebid/server/it/openrtb2/adnuntius/test-adnuntius-bid-request.json
  src/test/resources/org/prebid/server/it/openrtb2/adnuntius/test-auction-adnuntius-request.json
Labels: do not port

#3011 Yieldlab: Add Digital Service Act (DSA) support
  src/main/java/org/prebid/server/bidder/yieldlab/YieldlabBidder.java
  src/main/java/org/prebid/server/bidder/yieldlab/model/YieldlabDigitalServicesActResponse.java
  src/main/java/org/prebid/server/bidder/yieldlab/model/YieldlabResponse.java
  src/test/java/org/prebid/server/bidder/yieldlab/YieldlabBidderTest.java
Labels: do not port

#3036 Adprime: Resolve BidType from Mtype
  src/main/java/org/prebid/server/bidder/adprime/AdprimeBidder.java
  src/test/java/org/prebid/server/bidder/adprime/AdprimeBidderTest.java
  src/test/resources/org/prebid/server/it/openrtb2/adprime/test-adprime-bid-response.json
  src/test/resources/org/prebid/server/it/openrtb2/adprime/test-auction-adprime-response.json
Labels: do not port

#3055 Core: Add new zMaticoo bidder
  src/main/java/org/prebid/server/bidder/zmaticoo/ZMaticooBidder.java
  src/main/java/org/prebid/server/proto/openrtb/ext/request/zmaticoo/ExtImpZMaticoo.java
  src/main/java/org/prebid/server/spring/config/bidder/ZMaticooBidderConfiguration.java
  src/main/resources/bidder-config/zmaticoo.yaml
  src/main/resources/static/bidder-params/zmaticoo.json
  src/test/java/org/prebid/server/bidder/zmaticoo/ZMaticooBidderTest.java
  src/test/java/org/prebid/server/it/ZMaticooTest.java
  src/test/resources/org/prebid/server/it/openrtb2/zmaticoo/test-auction-zmaticoo-request.json
  src/test/resources/org/prebid/server/it/openrtb2/zmaticoo/test-auction-zmaticoo-response.json
  src/test/resources/org/prebid/server/it/openrtb2/zmaticoo/test-zmaticoo-bid-request.json
  src/test/resources/org/prebid/server/it/openrtb2/zmaticoo/test-zmaticoo-bid-response.json
  src/test/resources/org/prebid/server/it/test-application.properties
Labels: do not port

#3080 Test: Additonal coverage for geo
  src/test/groovy/org/prebid/server/functional/tests/GeoSpec.groovy
Labels: tests
