Repository prebid/prebid-server-java, pull requests merged in 2024-05, with the labels that each got.

#3162 Core: Async db client configuration
  docs/config-app.md
  src/main/java/org/prebid/server/spring/config/database/DatabaseConfiguration.java
  src/main/java/org/prebid/server/spring/config/database/model/ConnectionPoolSettings.java
  src/main/java/org/prebid/server/spring/config/database/properties/DatabaseConfigurationProperties.java
  src/main/resources/application.yaml
Labels: do not port, PBS 3.0

#3125 Update contact for mobfoxpb
  src/main/resources/bidder-config/mobfoxpb.yaml
Labels: do not port

#3141 Core: Add PostgreSQL SASL SCRAM-SHA-256 authentication support
  pom.xml
Labels: do not port

#3136 Test: `DSA` validation
  src/test/groovy/org/prebid/server/functional/model/request/auction/Dsa.groovy
  src/test/groovy/org/prebid/server/functional/model/response/auction/BidExt.groovy
  src/test/groovy/org/prebid/server/functional/model/response/auction/BidRejectionReason.groovy
  src/test/groovy/org/prebid/server/functional/model/response/auction/DsaResponse.groovy
  src/test/groovy/org/prebid/server/functional/tests/privacy/DsaSpec.groovy
Labels: tests

#3132 emxdigital: add geoscope to YAML
  src/main/resources/bidder-config/emxdigital.yaml
Labels: do not port

#3116 Fix Jacoco failure for the mvn verify command when all processes are successful
  pom.xml
Labels: do not port

#3108 Kargo: Adding GPP macros to bidder-info
  src/main/resources/bidder-config/kargo.yaml
Labels: do not port

#3105 Port: Criteo: add GPP macros
  src/main/resources/bidder-config/criteo.yaml
Labels: do not port

#3106 Rise: Add GPP macros
  src/main/resources/bidder-config/rise.yaml
Labels: do not port

#3112 Housekeeping: Remove PG leftovers
  docs/config-app.md
  pom.xml
  src/main/java/org/prebid/server/health/HealthMonitor.java
  src/main/java/org/prebid/server/spring/config/AopConfiguration.java
  src/main/resources/application.yaml
  src/test/java/org/prebid/server/health/HealthMonitorTest.java
  src/test/java/org/prebid/server/it/IntegrationTest.java
  src/test/resources/org/prebid/server/it/test-application.properties
Labels: do not port, PBS 3.0

#3151 Update properties description
  docs/config-app.md
Labels: do not port, PBS 3.0

#2728 Finished transition period for HTTP properties
  docs/config-app.md
  docs/metrics.md
  src/main/java/org/prebid/server/spring/config/server/application/ApplicationServerConfiguration.java
Labels: PBS 3.0

#2828 Convert some bidders as Generic aliases
  src/main/java/org/prebid/server/bidder/GenericBidder.java
  src/main/java/org/prebid/server/bidder/adrino/AdrinoBidder.java
  src/main/java/org/prebid/server/bidder/alkimi/AlkimiBidder.java
  src/main/java/org/prebid/server/bidder/ccx/CcxBidder.java
  src/main/java/org/prebid/server/bidder/infytv/InfytvBidder.java
  src/main/java/org/prebid/server/bidder/loopme/LoopmeBidder.java
  src/main/java/org/prebid/server/bidder/mgidx/MgidxBidder.java
  src/main/java/org/prebid/server/bidder/oms/OmsBidder.java
  src/main/java/org/prebid/server/bidder/zeta_global_ssp/ZetaGlobalSspBidder.java
  src/main/java/org/prebid/server/spring/config/bidder/AdrinoConfiguration.java
  src/main/java/org/prebid/server/spring/config/bidder/CcxConfiguration.java
  src/main/java/org/prebid/server/spring/config/bidder/InfytvConfiguration.java
  src/main/java/org/prebid/server/spring/config/bidder/LoopmeConfiguration.java
  src/main/java/org/prebid/server/spring/config/bidder/ZetaGlobalSspConfiguration.java
  src/main/resources/bidder-config/adrino.yaml
  src/main/resources/bidder-config/ccx.yaml
  src/main/resources/bidder-config/generic.yaml
  src/main/resources/bidder-config/infytv.yaml
  src/main/resources/bidder-config/loopme.yaml
  src/main/resources/bidder-config/zeta_global_ssp.yaml
  src/main/resources/static/bidder-params/zeta-global-ssp.json
  src/test/groovy/org/prebid/server/functional/testcontainers/PbsConfig.groovy
  src/test/java/org/prebid/server/bidder/adrino/AdrinoBidderTest.java
  src/test/java/org/prebid/server/bidder/ccx/CcxBidderTest.java
  src/test/java/org/prebid/server/bidder/infytv/InfytvBidderTest.java
  src/test/java/org/prebid/server/bidder/loopme/LoopmeBidderTest.java
  src/test/java/org/prebid/server/bidder/zeta_global_ssp/ZetaGlobalSspBidderTest.java
  src/test/java/org/prebid/server/it/ZetaGlobalSspTest.java
  src/test/resources/org/prebid/server/it/openrtb2/infytv/test-auction-infytv-request.json
  src/test/resources/org/prebid/server/it/openrtb2/infytv/test-infytv-bid-request-1.json
  src/test/resources/org/prebid/server/it/openrtb2/zetaglobalssp/test-auction-zeta-global-ssp-request.json
  src/test/resources/org/prebid/server/it/openrtb2/zetaglobalssp/test-auction-zeta-global-ssp-response.json
  src/test/resources/org/prebid/server/it/openrtb2/zetaglobalssp/test-zeta-global-ssp-bid-request.json
  src/test/resources/org/prebid/server/it/openrtb2/zetaglobalssp/test-zeta-global-ssp-bid-response.json
  src/test/resources/org/prebid/server/it/test-application.properties
Labels: PBS 3.0

#3177 Update metrics functional tests after change default PBS value
  src/test/groovy/org/prebid/server/functional/tests/MetricsSpec.groovy
Labels: tests

#3174 Update mgidx endpoints
  src/main/resources/bidder-config/mgidx.yaml
Labels: do not port

#3124 Tests: add coppa case, update acitivty
  src/test/groovy/org/prebid/server/functional/model/request/auction/GeoExtGeoProvider.groovy
  src/test/groovy/org/prebid/server/functional/tests/privacy/CoppaSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/privacy/GppTransmitPreciseGeoActivitiesSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/privacy/GppTransmitUfpdActivitiesSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/privacy/PrivacyBaseSpec.groovy
Labels: tests

#3168 Split ufpd and eids for TransmitUFPD tests
  src/test/groovy/org/prebid/server/functional/tests/privacy/GppTransmitUfpdActivitiesSpec.groovy
Labels: tests

#3180 Core: Reorganize Maven dependencies
  extra/bundle/pom.xml
  extra/modules/confiant-ad-quality/pom.xml
  extra/modules/pom.xml
  extra/pom.xml
  pom.xml
  src/test/groovy/org/prebid/server/functional/testcontainers/container/NetworkServiceContainer.groovy
  src/test/groovy/org/prebid/server/functional/tests/privacy/GppTransmitUfpdActivitiesSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/prometheus/PrometheusSpec.groovy
  src/test/java/org/prebid/server/bidder/adtelligent/AdtelligentBidderTest.java
Labels: do not port, PBS 3.0

#3187 Revert ZetaGlobalSsp Renaming
  src/main/resources/bidder-config/generic.yaml
  src/main/resources/static/bidder-params/zeta_global_ssp.json
  src/test/java/org/prebid/server/it/ZetaGlobalSspTest.java
  src/test/resources/org/prebid/server/it/openrtb2/zeta_global_ssp/test-auction-zeta_global_ssp-request.json
  src/test/resources/org/prebid/server/it/openrtb2/zeta_global_ssp/test-auction-zeta_global_ssp-response.json
  src/test/resources/org/prebid/server/it/openrtb2/zeta_global_ssp/test-zeta_global_ssp-bid-request.json
  src/test/resources/org/prebid/server/it/openrtb2/zeta_global_ssp/test-zeta_global_ssp-bid-response.json
  src/test/resources/org/prebid/server/it/test-application.properties
Labels: do not port

#3186 application.yaml: add switzerland to the default eea-countries
  src/main/resources/application.yaml
Labels: do not port

#3109 Adkernel: Unsecured endpoint url
  src/main/resources/bidder-config/adkernel.yaml
Labels: do not port

#3094 Add Roulax Adapter
  src/main/java/org/prebid/server/bidder/roulax/RoulaxBidder.java
  src/main/java/org/prebid/server/proto/openrtb/ext/request/roulax/ExtImpRoulax.java
  src/main/java/org/prebid/server/spring/config/bidder/RoulaxConfiguration.java
  src/main/resources/bidder-config/roulax.yaml
  src/main/resources/static/bidder-params/roulax.json
  src/test/java/org/prebid/server/bidder/roulax/RoulaxBidderTest.java
  src/test/java/org/prebid/server/it/RoulaxTest.java
  src/test/resources/org/prebid/server/it/openrtb2/roulax/test-auction-roulax-request.json
  src/test/resources/org/prebid/server/it/openrtb2/roulax/test-auction-roulax-response.json
  src/test/resources/org/prebid/server/it/openrtb2/roulax/test-roulax-bid-request.json
  src/test/resources/org/prebid/server/it/openrtb2/roulax/test-roulax-bid-response.json
  src/test/resources/org/prebid/server/it/test-application.properties
Labels: do not port

#3098 Add Consent Macros to Sonobi UserSync URL
  src/main/resources/bidder-config/sonobi.yaml
Labels: do not port

#3103 Core: Update `NextMillennium` bidder
  src/main/java/org/prebid/server/bidder/nextmillennium/NextMillenniumBidder.java
  src/main/resources/bidder-config/nextmillennium.yaml
  src/test/java/org/prebid/server/bidder/nextmillennium/NextMillenniumBidderTest.java
  src/test/resources/org/prebid/server/it/openrtb2/nextmillennium/test-auction-nextmillennium-response.json
  src/test/resources/org/prebid/server/it/openrtb2/nextmillennium/test-nextmillennium-bid-request.json
  src/test/resources/org/prebid/server/it/openrtb2/nextmillennium/test-nextmillennium-bid-response.json
Labels: do not port

#3087 Add Aso Adapter
  src/main/java/org/prebid/server/bidder/aso/AsoBidder.java
  src/main/java/org/prebid/server/proto/openrtb/ext/request/aso/ExtImpAso.java
  src/main/java/org/prebid/server/spring/config/bidder/AsoConfiguration.java
  src/main/resources/bidder-config/aso.yaml
  src/main/resources/static/bidder-params/aso.json
  src/test/java/org/prebid/server/bidder/aso/AsoBidderTest.java
  src/test/java/org/prebid/server/it/AsoTest.java
  src/test/java/org/prebid/server/it/BcmintTest.java
  src/test/java/org/prebid/server/it/BidAgencyTest.java
  src/test/resources/org/prebid/server/it/openrtb2/aso/test-aso-bid-request.json
  src/test/resources/org/prebid/server/it/openrtb2/aso/test-aso-bid-response.json
  src/test/resources/org/prebid/server/it/openrtb2/aso/test-auction-aso-request.json
  src/test/resources/org/prebid/server/it/openrtb2/aso/test-auction-aso-response.json
  src/test/resources/org/prebid/server/it/openrtb2/bcmint/test-auction-bcmint-request.json
  src/test/resources/org/prebid/server/it/openrtb2/bcmint/test-auction-bcmint-response.json
  src/test/resources/org/prebid/server/it/openrtb2/bcmint/test-bcmint-bid-request.json
  src/test/resources/org/prebid/server/it/openrtb2/bcmint/test-bcmint-bid-response.json
  src/test/resources/org/prebid/server/it/openrtb2/bidagency/test-auction-bidagency-request.json
  src/test/resources/org/prebid/server/it/openrtb2/bidagency/test-auction-bidagency-response.json
  src/test/resources/org/prebid/server/it/openrtb2/bidagency/test-bidagency-bid-request.json
  src/test/resources/org/prebid/server/it/openrtb2/bidagency/test-bidagency-bid-response.json
  src/test/resources/org/prebid/server/it/test-application.properties
Labels: do not port

#3093 Add Theadx Adapter
  src/main/java/org/prebid/server/bidder/theadx/TheadxBidder.java
  src/main/java/org/prebid/server/proto/openrtb/ext/request/theadx/ExtImpTheadx.java
  src/main/java/org/prebid/server/spring/config/bidder/TheadxConfiguration.java
  src/main/resources/bidder-config/theadx.yaml
  src/main/resources/static/bidder-params/theadx.json
  src/test/java/org/prebid/server/bidder/theadx/TheadxBidderTest.java
  src/test/java/org/prebid/server/it/TheadxTest.java
  src/test/resources/org/prebid/server/it/openrtb2/theadx/test-auction-theadx-request.json
  src/test/resources/org/prebid/server/it/openrtb2/theadx/test-auction-theadx-response.json
  src/test/resources/org/prebid/server/it/openrtb2/theadx/test-theadx-bid-request.json
  src/test/resources/org/prebid/server/it/openrtb2/theadx/test-theadx-bid-response.json
  src/test/resources/org/prebid/server/it/test-application.properties
Labels: do not port

#3101 Support Multi Imp Request for AdView
  src/main/java/org/prebid/server/bidder/adview/AdviewBidder.java
  src/test/java/org/prebid/server/bidder/adview/AdviewBidderTest.java
  src/test/resources/org/prebid/server/it/openrtb2/adview/test-adview-bid-response.json
  src/test/resources/org/prebid/server/it/openrtb2/adview/test-auction-adview-response.json
Labels: do not port

#3097 Deprecate SeatId for SeedingAlliance Adapter
  src/main/java/org/prebid/server/bidder/seedingAlliance/SeedingAllianceBidder.java
  src/main/java/org/prebid/server/proto/openrtb/ext/request/seedingalliance/ExtImpSeedingAlliance.java
  src/main/resources/static/bidder-params/seedingAlliance.json
  src/test/java/org/prebid/server/bidder/seedingAlliance/SeedingAllianceBidderTest.java
  src/test/java/org/prebid/server/it/SeedingAllianceTest.java
  src/test/resources/org/prebid/server/it/openrtb2/seedingAlliance/test-auction-seedingAlliance-request.json
  src/test/resources/org/prebid/server/it/openrtb2/seedingAlliance/test-seedingAlliance-bid-request.json
Labels: do not port

#3171 Tests: Eids
  src/test/groovy/org/prebid/server/functional/model/bidder/BidderName.groovy
  src/test/groovy/org/prebid/server/functional/model/request/auction/BidRequestExt.groovy
  src/test/groovy/org/prebid/server/functional/model/request/auction/Uid.groovy
  src/test/groovy/org/prebid/server/functional/model/request/auction/UidExt.groovy
  src/test/groovy/org/prebid/server/functional/tests/EidsSpec.groovy
Labels: tests

#3088 Test: Increase coverage for targeting spec
  src/test/groovy/org/prebid/server/functional/model/request/amp/AmpRequest.groovy
  src/test/groovy/org/prebid/server/functional/service/PrebidServerService.groovy
  src/test/groovy/org/prebid/server/functional/tests/TargetingSpec.groovy
Labels: tests

#3189 Test: `nbr` field
  src/test/groovy/org/prebid/server/functional/model/response/auction/BidResponse.groovy
  src/test/groovy/org/prebid/server/functional/model/response/auction/NoBidResponse.groovy
Labels: tests

#3114 Test: `BidResponse validations`
  src/test/groovy/org/prebid/server/functional/model/request/auction/Asset.groovy
  src/test/groovy/org/prebid/server/functional/model/request/auction/Banner.groovy
  src/test/groovy/org/prebid/server/functional/model/request/auction/Format.groovy
  src/test/groovy/org/prebid/server/functional/model/request/auction/Video.groovy
  src/test/groovy/org/prebid/server/functional/model/response/auction/Bid.groovy
  src/test/groovy/org/prebid/server/functional/testcontainers/scaffolding/Bidder.groovy
  src/test/groovy/org/prebid/server/functional/tests/AmpSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/BidderFormatSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsRulesSpec.groovy
Labels: tests

#3133 Add DSA Validations
  src/main/java/org/prebid/server/auction/DsaEnforcer.java
  src/main/java/org/prebid/server/auction/model/BidRejectionReason.java
  src/main/java/org/prebid/server/auction/requestfactory/Ortb2RequestFactory.java
  src/main/java/org/prebid/server/bidder/yieldlab/YieldlabBidder.java
  src/main/java/org/prebid/server/proto/openrtb/ext/request/DsaPublisherRender.java
  src/main/java/org/prebid/server/proto/openrtb/ext/request/DsaRequired.java
  src/main/java/org/prebid/server/proto/openrtb/ext/request/DsaTransparency.java
  src/main/java/org/prebid/server/proto/openrtb/ext/request/ExtRegsDsa.java
  src/main/java/org/prebid/server/proto/openrtb/ext/response/DsaAdvertiserRender.java
  src/main/java/org/prebid/server/proto/openrtb/ext/response/ExtBidDsa.java
  src/main/java/org/prebid/server/spring/config/ServiceConfiguration.java
  src/test/groovy/org/prebid/server/functional/model/request/auction/Dsa.groovy
  src/test/groovy/org/prebid/server/functional/model/response/auction/BidExt.groovy
  src/test/groovy/org/prebid/server/functional/model/response/auction/BidRejectionReason.groovy
  src/test/groovy/org/prebid/server/functional/model/response/auction/DsaResponse.groovy
  src/test/groovy/org/prebid/server/functional/tests/privacy/DsaSpec.groovy
  src/test/java/org/prebid/server/auction/DsaEnforcerTest.java
  src/test/java/org/prebid/server/auction/requestfactory/Ortb2RequestFactoryTest.java
  src/test/java/org/prebid/server/bidder/stroeercore/StroeerCoreBidderTest.java
  src/test/java/org/prebid/server/bidder/yieldlab/YieldlabBidderTest.java
Labels: do not port

#3194 Revert Rubicon Adapter Eid Enhancement
  src/main/java/org/prebid/server/bidder/rubicon/RubiconBidder.java
  src/test/java/org/prebid/server/bidder/rubicon/RubiconBidderTest.java
Labels: do not port
