Repository prebid/prebid-server-java, pull requests merged in 2024-11, with the labels that each got.

#3527 functional tests on module execution
  src/test/groovy/org/prebid/server/functional/model/config/EndpointExecutionPlan.groovy
  src/test/groovy/org/prebid/server/functional/model/config/ExecutionPlan.groovy
  src/test/groovy/org/prebid/server/functional/model/config/Stage.groovy
  src/test/groovy/org/prebid/server/functional/model/response/auction/ResponseAction.groovy
  src/test/groovy/org/prebid/server/functional/tests/module/GeneralModuleSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/module/ModuleBaseSpec.groovy
Labels: tests

#3528 Add tests for Zero Non Deal Bids Warning Only in Debug
  src/test/groovy/org/prebid/server/functional/model/request/auction/BidRequest.groovy
  src/test/groovy/org/prebid/server/functional/model/request/auction/DebugCondition.groovy
  src/test/groovy/org/prebid/server/functional/model/request/auction/Prebid.groovy
  src/test/groovy/org/prebid/server/functional/tests/BidValidationSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/DebugSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/SeatNonBidSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsBaseSpec.groovy
Labels: tests

#3532 Add functional tests for useFetchDataRate field
  src/test/groovy/org/prebid/server/functional/model/pricefloors/PriceFloorData.groovy
  src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsBaseSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsCurrencySpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsFetchingSpec.groovy
Labels: tests

#3522 Add Zero Non Deal Bids Warning Only in Debug
  src/main/java/org/prebid/server/auction/ExchangeService.java
  src/test/groovy/org/prebid/server/functional/model/request/auction/BidRequest.groovy
  src/test/groovy/org/prebid/server/functional/model/request/auction/DebugCondition.groovy
  src/test/groovy/org/prebid/server/functional/model/request/auction/Prebid.groovy
  src/test/groovy/org/prebid/server/functional/tests/BidValidationSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/DebugSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/SeatNonBidSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsBaseSpec.groovy
  src/test/java/org/prebid/server/auction/ExchangeServiceTest.java
Labels: do not port

#3523 Tests: Functional tests for OpenRTB battr strict logic
  src/test/groovy/org/prebid/server/functional/tests/module/ortb2blocking/Ortb2BlockingSpec.groovy
Labels: tests

#3486 Add useFetchDataRate for Price Floors
  src/main/java/org/prebid/server/floors/BasicPriceFloorProcessor.java
  src/main/java/org/prebid/server/floors/PriceFloorRulesValidator.java
  src/main/java/org/prebid/server/floors/model/PriceFloorData.java
  src/test/groovy/org/prebid/server/functional/model/pricefloors/PriceFloorData.groovy
  src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsBaseSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsCurrencySpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsFetchingSpec.groovy
  src/test/java/org/prebid/server/floors/BasicPriceFloorProcessorTest.java
  src/test/java/org/prebid/server/floors/PriceFloorRulesValidatorTest.java
Labels: do not port

#3525 Module Execution: Add Property to Require Account Config
  docs/metrics.md
  extra/modules/confiant-ad-quality/src/main/java/org/prebid/server/hooks/modules/com/confiant/adquality/v1/ConfiantAdQualityBidResponsesScanHook.java
  extra/modules/confiant-ad-quality/src/main/java/org/prebid/server/hooks/modules/com/confiant/adquality/v1/model/InvocationResultImpl.java
  extra/modules/fiftyone-devicedetection/src/main/java/org/prebid/server/hooks/modules/fiftyone/devicedetection/v1/hooks/FiftyOneDeviceDetectionEntrypointHook.java
  extra/modules/fiftyone-devicedetection/src/main/java/org/prebid/server/hooks/modules/fiftyone/devicedetection/v1/hooks/FiftyOneDeviceDetectionRawAuctionRequestHook.java
  extra/modules/fiftyone-devicedetection/src/main/java/org/prebid/server/hooks/modules/fiftyone/devicedetection/v1/model/InvocationResultImpl.java
  extra/modules/ortb2-blocking/src/main/java/org/prebid/server/hooks/modules/ortb2/blocking/v1/Ortb2BlockingBidderRequestHook.java
  extra/modules/ortb2-blocking/src/main/java/org/prebid/server/hooks/modules/ortb2/blocking/v1/Ortb2BlockingRawBidderResponseHook.java
  extra/modules/ortb2-blocking/src/test/java/org/prebid/server/hooks/modules/ortb2/blocking/v1/Ortb2BlockingBidderRequestHookTest.java
  extra/modules/ortb2-blocking/src/test/java/org/prebid/server/hooks/modules/ortb2/blocking/v1/Ortb2BlockingRawBidderResponseHookTest.java
  extra/modules/pb-response-correction/src/main/java/org/prebid/server/hooks/modules/pb/response/correction/v1/ResponseCorrectionAllProcessedBidResponsesHook.java
  extra/modules/pb-response-correction/src/main/java/org/prebid/server/hooks/modules/pb/response/correction/v1/model/InvocationResultImpl.java
  extra/modules/pb-richmedia-filter/src/main/java/org/prebid/server/hooks/modules/pb/richmedia/filter/v1/PbRichmediaFilterAllProcessedBidResponsesHook.java
  extra/modules/pb-richmedia-filter/src/main/java/org/prebid/server/hooks/modules/pb/richmedia/filter/v1/model/InvocationResultImpl.java
  src/main/java/org/prebid/server/auction/ExchangeService.java
  src/main/java/org/prebid/server/hooks/execution/GroupExecutor.java
  src/main/java/org/prebid/server/hooks/execution/GroupResult.java
  src/main/java/org/prebid/server/hooks/execution/HookStageExecutor.java
  src/main/java/org/prebid/server/hooks/execution/StageExecutor.java
  src/main/java/org/prebid/server/hooks/execution/model/ExecutionAction.java
  src/main/java/org/prebid/server/hooks/v1/InvocationAction.java
  src/main/java/org/prebid/server/hooks/v1/InvocationResultImpl.java
  src/main/java/org/prebid/server/metric/MetricName.java
  src/main/java/org/prebid/server/metric/Metrics.java
  src/main/java/org/prebid/server/metric/StageMetrics.java
  src/main/java/org/prebid/server/spring/config/HooksConfiguration.java
  src/test/groovy/org/prebid/server/functional/model/config/EndpointExecutionPlan.groovy
  src/test/groovy/org/prebid/server/functional/model/config/ExecutionPlan.groovy
  src/test/groovy/org/prebid/server/functional/model/config/Stage.groovy
  src/test/groovy/org/prebid/server/functional/model/response/auction/ResponseAction.groovy
  src/test/groovy/org/prebid/server/functional/tests/module/GeneralModuleSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/module/ModuleBaseSpec.groovy
  src/test/java/org/prebid/server/hooks/execution/HookStageExecutorTest.java
  src/test/java/org/prebid/server/hooks/v1/InvocationResultUtils.java
  src/test/java/org/prebid/server/it/hooks/SampleItAuctionResponseHook.java
  src/test/java/org/prebid/server/it/hooks/SampleItBidderRequestHook.java
  src/test/java/org/prebid/server/it/hooks/SampleItEntrypointHook.java
  src/test/java/org/prebid/server/it/hooks/SampleItProcessedAuctionRequestHook.java
  src/test/java/org/prebid/server/it/hooks/SampleItProcessedBidderResponseHook.java
  src/test/java/org/prebid/server/it/hooks/SampleItRawBidderResponseHook.java
  src/test/java/org/prebid/server/it/hooks/SampleItRejectingBidderRequestHook.java
  src/test/java/org/prebid/server/it/hooks/SampleItRejectingProcessedAuctionRequestHook.java
  src/test/java/org/prebid/server/it/hooks/SampleItRejectingProcessedBidderResponseHook.java
  src/test/java/org/prebid/server/it/hooks/SampleItRejectingRawAuctionRequestHook.java
  src/test/java/org/prebid/server/it/hooks/SampleItRejectingRawBidderResponseHook.java
  src/test/java/org/prebid/server/metric/MetricsTest.java
Labels: do not port

#3544 Tests: Bid Adjustments Feature
  src/test/groovy/org/prebid/server/functional/model/config/AccountAuctionConfig.groovy
  src/test/groovy/org/prebid/server/functional/model/request/auction/AdjustmentRule.groovy
  src/test/groovy/org/prebid/server/functional/model/request/auction/AdjustmentType.groovy
  src/test/groovy/org/prebid/server/functional/model/request/auction/BidAdjustment.groovy
  src/test/groovy/org/prebid/server/functional/model/request/auction/BidAdjustmentFactors.groovy
  src/test/groovy/org/prebid/server/functional/model/request/auction/BidAdjustmentMediaType.groovy
  src/test/groovy/org/prebid/server/functional/model/request/auction/BidAdjustmentRule.groovy
  src/test/groovy/org/prebid/server/functional/model/request/auction/BidRequest.groovy
  src/test/groovy/org/prebid/server/functional/model/request/auction/Prebid.groovy
  src/test/groovy/org/prebid/server/functional/tests/BidAdjustmentSpec.groovy
Labels: tests

#3546 Sample HttpBidderRequester Logs
  src/main/java/org/prebid/server/bidder/HttpBidderRequester.java
  src/main/java/org/prebid/server/spring/config/ServiceConfiguration.java
  src/test/java/org/prebid/server/bidder/HttpBidderRequesterTest.java
Labels: do not port

#3542 Bid Adjustments Feature
  docs/application-settings.md
  src/main/java/org/prebid/server/auction/BidsAdjuster.java
  src/main/java/org/prebid/server/auction/model/AuctionContext.java
  src/main/java/org/prebid/server/auction/requestfactory/AuctionRequestFactory.java
  src/main/java/org/prebid/server/bidadjustments/BidAdjustmentRulesValidator.java
  src/main/java/org/prebid/server/bidadjustments/BidAdjustmentsProcessor.java
  src/main/java/org/prebid/server/bidadjustments/BidAdjustmentsResolver.java
  src/main/java/org/prebid/server/bidadjustments/BidAdjustmentsRetriever.java
  src/main/java/org/prebid/server/bidadjustments/model/BidAdjustmentType.java
  src/main/java/org/prebid/server/bidadjustments/model/BidAdjustments.java
  src/main/java/org/prebid/server/proto/openrtb/ext/request/ExtRequestBidAdjustments.java
  src/main/java/org/prebid/server/proto/openrtb/ext/request/ExtRequestBidAdjustmentsRule.java
  src/main/java/org/prebid/server/proto/openrtb/ext/request/ExtRequestPrebid.java
  src/main/java/org/prebid/server/proto/openrtb/ext/request/ImpMediaType.java
  src/main/java/org/prebid/server/settings/model/AccountAuctionConfig.java
  src/main/java/org/prebid/server/spring/config/ServiceConfiguration.java
  src/test/groovy/org/prebid/server/functional/model/config/AccountAuctionConfig.groovy
  src/test/groovy/org/prebid/server/functional/model/request/auction/AdjustmentRule.groovy
  src/test/groovy/org/prebid/server/functional/model/request/auction/AdjustmentType.groovy
  src/test/groovy/org/prebid/server/functional/model/request/auction/BidAdjustment.groovy
  src/test/groovy/org/prebid/server/functional/model/request/auction/BidAdjustmentFactors.groovy
  src/test/groovy/org/prebid/server/functional/model/request/auction/BidAdjustmentMediaType.groovy
  src/test/groovy/org/prebid/server/functional/model/request/auction/BidAdjustmentRule.groovy
  src/test/groovy/org/prebid/server/functional/model/request/auction/BidRequest.groovy
  src/test/groovy/org/prebid/server/functional/model/request/auction/Prebid.groovy
  src/test/groovy/org/prebid/server/functional/tests/BidAdjustmentSpec.groovy
  src/test/java/org/prebid/server/auction/BidsAdjusterTest.java
  src/test/java/org/prebid/server/auction/requestfactory/AuctionRequestFactoryTest.java
  src/test/java/org/prebid/server/bidadjustments/BidAdjustmentRulesValidatorTest.java
  src/test/java/org/prebid/server/bidadjustments/BidAdjustmentsProcessorTest.java
  src/test/java/org/prebid/server/bidadjustments/BidAdjustmentsResolverTest.java
  src/test/java/org/prebid/server/bidadjustments/BidAdjustmentsRetrieverTest.java
  src/test/java/org/prebid/server/bidadjustments/model/BidAdjustmentsTest.java
Labels: do not port

#3552 Remove Redundant Logback Dependency
  extra/modules/fiftyone-devicedetection/pom.xml
Labels: do not port

#3554 Test: Debug metrics
  src/test/groovy/org/prebid/server/functional/tests/DebugSpec.groovy
Labels: tests

#3548 Add Debug Metrics
  docs/metrics.md
  src/main/java/org/prebid/server/auction/ExchangeService.java
  src/main/java/org/prebid/server/metric/MetricName.java
  src/main/java/org/prebid/server/metric/Metrics.java
  src/test/groovy/org/prebid/server/functional/tests/DebugSpec.groovy
  src/test/java/org/prebid/server/auction/ExchangeServiceTest.java
  src/test/java/org/prebid/server/metric/MetricsTest.java
Labels: do not port

#3555 Update Gothamads account passing
  src/main/java/org/prebid/server/bidder/gotthamads/GothamAdsBidder.java
  src/test/java/org/prebid/server/bidder/gothamads/GothamAdsBidderTest.java
Labels: bug, do not port

#3556 Krushmedia: Usersync update
  src/main/resources/bidder-config/krushmedia.yaml
Labels: do not port

#3571 AlgoriX: Add GVL vendor ID
  src/main/resources/bidder-config/algorix.yaml
Labels: do not port

#3560 Update code-reviews.md
  docs/developers/code-reviews.md
Labels: do not port

#3563 IX: fix ix adapter handling of paapi config
  src/main/java/org/prebid/server/bidder/ix/IxBidder.java
  src/main/java/org/prebid/server/bidder/ix/model/response/AuctionConfigExtBidResponse.java
  src/main/java/org/prebid/server/bidder/ix/model/response/IxExtBidResponse.java
  src/test/java/org/prebid/server/bidder/ix/IxBidderTest.java
  src/test/resources/org/prebid/server/it/openrtb2/ix/test-auction-ix-request.json
  src/test/resources/org/prebid/server/it/openrtb2/ix/test-auction-ix-response.json
  src/test/resources/org/prebid/server/it/openrtb2/ix/test-ix-bid-request.json
  src/test/resources/org/prebid/server/it/openrtb2/ix/test-ix-bid-response.json
Labels: do not port

#3585 Housekeeping: Update pull_request_template.md
  .github/pull_request_template.md
Labels: do not port

#3578 Richaudience Bidder: Add Redirect Sync
  src/main/resources/bidder-config/richaudience.yaml
Labels: do not port
