Repository prebid/prebid-server-java, pull requests merged in 2024-02, with the labels that each got.

#2939 Cover DSA fields and validation
  src/test/groovy/org/prebid/server/functional/model/request/auction/DsaTransparency.groovy
  src/test/groovy/org/prebid/server/functional/model/request/auction/RegsDsa.groovy
  src/test/groovy/org/prebid/server/functional/model/request/auction/RegsExt.groovy
  src/test/groovy/org/prebid/server/functional/model/request/auction/ReqsDsaRequiredType.groovy
  src/test/groovy/org/prebid/server/functional/model/response/auction/BidExt.groovy
  src/test/groovy/org/prebid/server/functional/model/response/auction/BidExtDsa.groovy
  src/test/groovy/org/prebid/server/functional/tests/DsaSpec.groovy
Labels: tests

#2860 Core: added warning in case of invalid targeting key prefix
  src/main/java/org/prebid/server/auction/BidResponseCreator.java
  src/test/groovy/org/prebid/server/functional/model/response/auction/ErrorType.groovy
  src/test/groovy/org/prebid/server/functional/tests/TargetingSpec.groovy
  src/test/java/org/prebid/server/auction/BidResponseCreatorTest.java
Labels: do not port

#2922 Core: Add new `AdQuery` bidder
  src/main/java/org/prebid/server/bidder/adquery/AdQueryBidder.java
  src/main/java/org/prebid/server/bidder/adquery/model/request/AdQueryRequest.java
  src/main/java/org/prebid/server/bidder/adquery/model/response/AdQueryDataResponse.java
  src/main/java/org/prebid/server/bidder/adquery/model/response/AdQueryMediaType.java
  src/main/java/org/prebid/server/bidder/adquery/model/response/AdQueryResponse.java
  src/main/java/org/prebid/server/proto/openrtb/ext/request/adquery/ExtImpAdQuery.java
  src/main/java/org/prebid/server/spring/config/bidder/AdQueryConfiguration.java
  src/main/resources/bidder-config/adquery.yaml
  src/main/resources/static/bidder-params/adquery.json
  src/test/java/org/prebid/server/bidder/adquery/AdQueryBidderTest.java
  src/test/java/org/prebid/server/it/AdQueryTest.java
  src/test/resources/org/prebid/server/it/openrtb2/adquery/test-adquery-bid-request.json
  src/test/resources/org/prebid/server/it/openrtb2/adquery/test-adquery-bid-response.json
  src/test/resources/org/prebid/server/it/openrtb2/adquery/test-auction-adquery-request.json
  src/test/resources/org/prebid/server/it/openrtb2/adquery/test-auction-adquery-response.json
  src/test/resources/org/prebid/server/it/test-application.properties
Labels: do not port

#2959 Tests: Default account DSA support
  src/test/groovy/org/prebid/server/functional/model/config/AccountDsaConfig.groovy
  src/test/groovy/org/prebid/server/functional/model/config/AccountPrivacyConfig.groovy
  src/test/groovy/org/prebid/server/functional/model/request/auction/Dsa.groovy
  src/test/groovy/org/prebid/server/functional/model/request/auction/DsaDataToPub.groovy
  src/test/groovy/org/prebid/server/functional/model/request/auction/DsaPubRender.groovy
  src/test/groovy/org/prebid/server/functional/model/request/auction/DsaRequired.groovy
  src/test/groovy/org/prebid/server/functional/model/request/auction/DsaTransparency.groovy
  src/test/groovy/org/prebid/server/functional/model/request/auction/DsaTransparencyParam.groovy
  src/test/groovy/org/prebid/server/functional/model/request/auction/RegsDsa.groovy
  src/test/groovy/org/prebid/server/functional/model/request/auction/RegsExt.groovy
  src/test/groovy/org/prebid/server/functional/model/request/auction/ReqsDsaRequiredType.groovy
  src/test/groovy/org/prebid/server/functional/model/response/auction/BidExt.groovy
  src/test/groovy/org/prebid/server/functional/model/response/auction/BidExtDsa.groovy
  src/test/groovy/org/prebid/server/functional/model/response/auction/Dsa.groovy
  src/test/groovy/org/prebid/server/functional/model/response/auction/DsaAdRender.groovy
  src/test/groovy/org/prebid/server/functional/tests/DsaSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/privacy/DsaSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/privacy/PrivacyBaseSpec.groovy
Labels: tests, do not port

#2971 GitHub: changed workflow trigger for several jobs
  .github/workflows/docker-image-publish.yml
  .github/workflows/release-asset-publish.yml
Labels: do not port

#2967 Boldwin: get bid type from bid.mtype
  src/main/java/org/prebid/server/bidder/boldwin/BoldwinBidder.java
  src/test/java/org/prebid/server/bidder/boldwin/BoldwinBidderTest.java
  src/test/resources/org/prebid/server/it/openrtb2/boldwin/test-auction-boldwin-response.json
  src/test/resources/org/prebid/server/it/openrtb2/boldwin/test-boldwin-bid-response.json
Labels: do not port

#2957 Refactoring: extract floors configuration processing
  src/main/java/org/prebid/server/floors/BasicPriceFloorProcessor.java
  src/main/java/org/prebid/server/floors/BasicPriceFloorResolver.java
  src/main/java/org/prebid/server/util/IterableUtil.java
  src/main/java/org/prebid/server/util/StreamUtil.java
  src/main/java/org/prebid/server/util/algorithms/CartesianProductIterator.java
  src/main/java/org/prebid/server/util/algorithms/IterablesUnionView.java
  src/main/java/org/prebid/server/util/algorithms/random/RandomAnyWeightedEntrySupplier.java
  src/main/java/org/prebid/server/util/algorithms/random/RandomPositiveWeightedEntrySupplier.java
  src/main/java/org/prebid/server/util/algorithms/random/RandomWeightedEntrySupplier.java
  src/main/java/org/prebid/server/util/dsl/config/PrebidConfigMatchingStrategy.java
  src/main/java/org/prebid/server/util/dsl/config/PrebidConfigParameter.java
  src/main/java/org/prebid/server/util/dsl/config/PrebidConfigParameters.java
  src/main/java/org/prebid/server/util/dsl/config/PrebidConfigSchema.java
  src/main/java/org/prebid/server/util/dsl/config/PrebidConfigSource.java
  src/main/java/org/prebid/server/util/dsl/config/impl/MostAccurateCombinationStrategy.java
  src/main/java/org/prebid/server/util/dsl/config/impl/SimpleDirectParameter.java
  src/main/java/org/prebid/server/util/dsl/config/impl/SimpleParameters.java
  src/main/java/org/prebid/server/util/dsl/config/impl/SimpleSource.java
  src/test/java/org/prebid/server/util/IterableUtilTest.java
  src/test/java/org/prebid/server/util/algorithms/CartesianProductIteratorTest.java
  src/test/java/org/prebid/server/util/algorithms/IterableUnionViewTest.java
  src/test/java/org/prebid/server/util/algorithms/random/RandomAnyWeightedEntrySupplierTest.java
  src/test/java/org/prebid/server/util/algorithms/random/RandomPositiveWeightedEntrySupplierTest.java
  src/test/java/org/prebid/server/util/dsl/config/impl/MostAccurateCombinationStrategyTest.java
Labels: do not port

#2963 Add functional tests for support testing label header
  src/test/groovy/org/prebid/server/functional/model/config/AccountAuctionConfig.groovy
  src/test/groovy/org/prebid/server/functional/model/config/CookieDeprecation.groovy
  src/test/groovy/org/prebid/server/functional/model/config/PrivacySandbox.groovy
  src/test/groovy/org/prebid/server/functional/model/request/auction/DeviceExt.groovy
  src/test/groovy/org/prebid/server/functional/model/response/cookiesync/RawCookieSyncResponse.groovy
  src/test/groovy/org/prebid/server/functional/service/PrebidServerService.groovy
  src/test/groovy/org/prebid/server/functional/tests/AuctionSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/CookieSyncSpec.groovy
  src/test/groovy/org/prebid/server/functional/util/HttpUtil.groovy
Labels: tests

#2976 Refactoring: Add `TimeoutContext`
  src/main/java/org/prebid/server/auction/BidResponseCreator.java
  src/main/java/org/prebid/server/auction/ExchangeService.java
  src/main/java/org/prebid/server/auction/PrivacyEnforcementService.java
  src/main/java/org/prebid/server/auction/model/AuctionContext.java
  src/main/java/org/prebid/server/auction/model/TimeoutContext.java
  src/main/java/org/prebid/server/auction/privacycontextfactory/AmpPrivacyContextFactory.java
  src/main/java/org/prebid/server/auction/requestfactory/Ortb2RequestFactory.java
  src/main/java/org/prebid/server/cache/CacheService.java
  src/main/java/org/prebid/server/deals/UserAdditionalInfoService.java
  src/main/java/org/prebid/server/spring/config/ServiceConfiguration.java
  src/test/java/org/prebid/server/analytics/reporter/pubstack/PubstackEventHandlerTest.java
  src/test/java/org/prebid/server/auction/BidResponseCreatorTest.java
  src/test/java/org/prebid/server/auction/ExchangeServiceTest.java
  src/test/java/org/prebid/server/auction/PrivacyEnforcementServiceTest.java
  src/test/java/org/prebid/server/auction/privacycontextfactory/AmpPrivacyContextFactoryTest.java
  src/test/java/org/prebid/server/auction/requestfactory/Ortb2RequestFactoryTest.java
  src/test/java/org/prebid/server/cache/CacheServiceTest.java
  src/test/java/org/prebid/server/deals/UserAdditionalInfoServiceTest.java
  src/test/java/org/prebid/server/handler/openrtb2/AmpHandlerTest.java
  src/test/java/org/prebid/server/handler/openrtb2/AuctionHandlerTest.java
  src/test/java/org/prebid/server/handler/openrtb2/VideoHandlerTest.java
Labels: do not port

#3013 Disable module tests for default maven verify runs
  .github/workflows/pr-module-functional-tests.yml
  docs/developers/functional-tests.md
  pom.xml
Labels: refactoring, do not port

#3015 Tests: Fix flaky tests
  src/test/groovy/org/prebid/server/functional/tests/module/richmedia/RichMediaFilterSpec.groovy
Labels: tests
