Repository prebid/prebid-server-java, pull requests merged in 2025-09, with the labels that each got.

#4162 Kobler: Add app support
  src/main/resources/bidder-config/kobler.yaml
Labels: do not port

#4165 Onetag Adapter: imp.ext read generalization
  src/main/java/org/prebid/server/bidder/onetag/OnetagBidder.java
  src/test/java/org/prebid/server/bidder/onetag/OnetagBidderTest.java
  src/test/resources/org/prebid/server/it/openrtb2/onetag/test-onetag-bid-request.json
Labels: do not port

#4170 Dependencies: Bump GPP library version
  extra/pom.xml
Labels: dependencies, do not port

#4163 Smartadserver: Add second endpoint for programmatic guaranteed
  src/main/java/org/prebid/server/bidder/smartadserver/SmartadserverBidder.java
  src/main/java/org/prebid/server/proto/openrtb/ext/request/smartadserver/ExtImpSmartadserver.java
  src/main/java/org/prebid/server/spring/config/bidder/SmartadserverConfiguration.java
  src/main/resources/bidder-config/smartadserver.yaml
  src/test/java/org/prebid/server/bidder/smartadserver/SmartadserverBidderTest.java
  src/test/java/org/prebid/server/it/SmartadserverTest.java
  src/test/resources/org/prebid/server/it/openrtb2/smartadserver/test-auction-smartadserver-request.json
  src/test/resources/org/prebid/server/it/openrtb2/smartadserver/test-smartadserver-bid-request.json
  src/test/resources/org/prebid/server/it/test-application.properties
Labels: do not port

#4056 Tests: Add profiles
  src/test/groovy/org/prebid/server/functional/model/config/AccountAuctionConfig.groovy
  src/test/groovy/org/prebid/server/functional/model/config/AccountProfilesConfigs.groovy
  src/test/groovy/org/prebid/server/functional/model/db/StoredProfileImp.groovy
  src/test/groovy/org/prebid/server/functional/model/db/StoredProfileRequest.groovy
  src/test/groovy/org/prebid/server/functional/model/db/StoredRequest.groovy
  src/test/groovy/org/prebid/server/functional/model/db/StoredResponse.groovy
  src/test/groovy/org/prebid/server/functional/model/db/typeconverter/BidRequestConfigTypeConverter.groovy
  src/test/groovy/org/prebid/server/functional/model/db/typeconverter/BidResponseConfigTypeConverter.groovy
  src/test/groovy/org/prebid/server/functional/model/db/typeconverter/ProfileMergePrecedenceConvert.groovy
  src/test/groovy/org/prebid/server/functional/model/db/typeconverter/ProfileTypeConvert.groovy
  src/test/groovy/org/prebid/server/functional/model/filesystem/FileSystemAccountsConfig.groovy
  src/test/groovy/org/prebid/server/functional/model/request/auction/Banner.groovy
  src/test/groovy/org/prebid/server/functional/model/request/auction/BidRequestExt.groovy
  src/test/groovy/org/prebid/server/functional/model/request/auction/Device.groovy
  src/test/groovy/org/prebid/server/functional/model/request/auction/Format.groovy
  src/test/groovy/org/prebid/server/functional/model/request/auction/ImpExtPrebid.groovy
  src/test/groovy/org/prebid/server/functional/model/request/auction/Prebid.groovy
  src/test/groovy/org/prebid/server/functional/model/request/auction/Site.groovy
  src/test/groovy/org/prebid/server/functional/model/request/auction/SiteExtData.groovy
  src/test/groovy/org/prebid/server/functional/model/request/profile/ImpProfile.groovy
  src/test/groovy/org/prebid/server/functional/model/request/profile/Profile.groovy
  src/test/groovy/org/prebid/server/functional/model/request/profile/ProfileMergePrecedence.groovy
  src/test/groovy/org/prebid/server/functional/model/request/profile/ProfileType.groovy
  src/test/groovy/org/prebid/server/functional/model/request/profile/RequestProfile.groovy
  src/test/groovy/org/prebid/server/functional/model/response/auction/BidResponse.groovy
  src/test/groovy/org/prebid/server/functional/repository/HibernateRepositoryService.groovy
  src/test/groovy/org/prebid/server/functional/repository/dao/ProfileImpDao.groovy
  src/test/groovy/org/prebid/server/functional/repository/dao/ProfileRequestDao.groovy
  src/test/groovy/org/prebid/server/functional/testcontainers/PbsConfig.groovy
  src/test/groovy/org/prebid/server/functional/testcontainers/container/PrebidServerContainer.groovy
  src/test/groovy/org/prebid/server/functional/tests/ProfileSpec.groovy
  src/test/groovy/org/prebid/server/functional/util/ObjectMapperWrapper.groovy
  src/test/groovy/org/prebid/server/functional/util/PBSUtils.groovy
  src/test/resources/org/prebid/server/functional/db_mysql_schema.sql
Labels: tests

#4172 Fix issue with invalid functional tests
  src/test/groovy/org/prebid/server/functional/model/request/auction/IxDiag.groovy
  src/test/groovy/org/prebid/server/functional/util/PBSUtils.groovy
Labels: tests, do not port

#4178 Profile: Fix NPE. Make DB config optional.
  src/main/java/org/prebid/server/auction/externalortb/ProfilesProcessor.java
  src/main/java/org/prebid/server/settings/DatabaseApplicationSettings.java
  src/main/java/org/prebid/server/settings/FileApplicationSettings.java
  src/main/java/org/prebid/server/spring/config/SettingsConfiguration.java
  src/test/groovy/org/prebid/server/functional/model/request/auction/Banner.groovy
  src/test/groovy/org/prebid/server/functional/model/request/auction/Format.groovy
  src/test/groovy/org/prebid/server/functional/model/request/auction/Video.groovy
  src/test/groovy/org/prebid/server/functional/model/response/auction/Bid.groovy
  src/test/groovy/org/prebid/server/functional/testcontainers/PbsConfig.groovy
  src/test/groovy/org/prebid/server/functional/testcontainers/scaffolding/Bidder.groovy
  src/test/groovy/org/prebid/server/functional/tests/AmpSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/BidderFormatSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/ProfileSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/SeatNonBidSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsRulesSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/storage/AmpS3Spec.groovy
Labels: do not port

#4184 Connatix Bid Adapter: adds GPP macros
  src/main/resources/bidder-config/connatix.yaml
Labels: do not port

#4135 SSPBC Adapter: adapter update
  src/main/java/org/prebid/server/bidder/sspbc/SspbcBidder.java
  src/main/java/org/prebid/server/bidder/sspbc/SspbcRequest.java
  src/main/java/org/prebid/server/bidder/sspbc/request/SspbcRequestType.java
  src/main/resources/bidder-config/sspbc.yaml
  src/test/java/org/prebid/server/bidder/sspbc/SspbcBidderTest.java
  src/test/resources/org/prebid/server/it/openrtb2/sspbc/test-auction-sspbc-request.json
  src/test/resources/org/prebid/server/it/openrtb2/sspbc/test-auction-sspbc-response.json
  src/test/resources/org/prebid/server/it/openrtb2/sspbc/test-sspbc-bid-request.json
  src/test/resources/org/prebid/server/it/openrtb2/sspbc/test-sspbc-bid-response.json
Labels: do not port

#4189 Documentation: Local dev request examples
  sample/configs/localdev-config.yaml
  sample/profiles/README.md
  sample/requests/localdev-test-request.http
  sample/requests/localdev-test-stored-auction-response.http
  sample/requests/localdev-test-stored-bidder-response.http
  sample/stored/sample-stored-auction-response.json
  sample/stored/sample-stored-bidder-response.json
Labels: do not port

#4191 Test: Fix default value of targeting.hb_pb
  src/test/groovy/org/prebid/server/functional/tests/TargetingSpec.groovy
Labels: tests

#4195 Test: Bidder Specific Imp Level Params Should Apply to a Specific Alias
  src/test/groovy/org/prebid/server/functional/tests/ImpRequestSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/privacy/GdprSetUidSpec.groovy
Labels: tests

#4192 Test: Add a warning for when targeting attributes are truncated
  src/test/groovy/org/prebid/server/functional/testcontainers/PbsConfig.groovy
  src/test/groovy/org/prebid/server/functional/testcontainers/container/PrebidServerContainer.groovy
  src/test/groovy/org/prebid/server/functional/tests/CacheSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/TargetingSpec.groovy
Labels: tests
