Repository prebid/prebid-server-java, pull requests merged in 2025-04, with the labels that each got.

#3870 Dependencies: bump IAB GPP library
  extra/pom.xml
  src/main/java/org/prebid/server/activity/infrastructure/privacy/PrivacySection.java
  src/main/java/org/prebid/server/activity/infrastructure/privacy/uscustomlogic/reader/USCaliforniaGppReader.java
  src/main/java/org/prebid/server/activity/infrastructure/privacy/uscustomlogic/reader/USColoradoGppReader.java
  src/main/java/org/prebid/server/activity/infrastructure/privacy/uscustomlogic/reader/USConnecticutGppReader.java
  src/main/java/org/prebid/server/activity/infrastructure/privacy/uscustomlogic/reader/USUtahGppReader.java
  src/main/java/org/prebid/server/activity/infrastructure/privacy/uscustomlogic/reader/USVirginiaGppReader.java
  src/main/java/org/prebid/server/activity/infrastructure/privacy/usnat/reader/USMappedCaliforniaGppReader.java
  src/main/java/org/prebid/server/activity/infrastructure/privacy/usnat/reader/USMappedColoradoGppReader.java
  src/main/java/org/prebid/server/activity/infrastructure/privacy/usnat/reader/USMappedConnecticutGppReader.java
  src/main/java/org/prebid/server/activity/infrastructure/privacy/usnat/reader/USMappedUtahGppReader.java
  src/main/java/org/prebid/server/activity/infrastructure/privacy/usnat/reader/USMappedVirginiaGppReader.java
  src/main/java/org/prebid/server/activity/infrastructure/privacy/usnat/reader/USNationalGppReader.java
  src/test/groovy/org/prebid/server/functional/model/config/UsNationalPrivacySection.groovy
  src/test/groovy/org/prebid/server/functional/model/request/GppSectionId.groovy
  src/test/groovy/org/prebid/server/functional/util/privacy/gpp/GppConsent.groovy
  src/test/groovy/org/prebid/server/functional/util/privacy/gpp/UsCaV1Consent.groovy
  src/test/groovy/org/prebid/server/functional/util/privacy/gpp/UsCoV1Consent.groovy
  src/test/groovy/org/prebid/server/functional/util/privacy/gpp/UsCtV1Consent.groovy
  src/test/groovy/org/prebid/server/functional/util/privacy/gpp/UsNatV1Consent.groovy
  src/test/groovy/org/prebid/server/functional/util/privacy/gpp/UsUtV1Consent.groovy
  src/test/groovy/org/prebid/server/functional/util/privacy/gpp/UsVaV1Consent.groovy
  src/test/java/org/prebid/server/activity/infrastructure/privacy/uscustomlogic/reader/USCaliforniaGppReaderTest.java
  src/test/java/org/prebid/server/activity/infrastructure/privacy/uscustomlogic/reader/USColoradoGppReaderTest.java
  src/test/java/org/prebid/server/activity/infrastructure/privacy/uscustomlogic/reader/USConnecticutGppReaderTest.java
  src/test/java/org/prebid/server/activity/infrastructure/privacy/uscustomlogic/reader/USUtahGppReaderTest.java
  src/test/java/org/prebid/server/activity/infrastructure/privacy/uscustomlogic/reader/USVirginiaGppReaderTest.java
  src/test/java/org/prebid/server/activity/infrastructure/privacy/usnat/reader/USMappedCaliforniaGppReaderTest.java
  src/test/java/org/prebid/server/activity/infrastructure/privacy/usnat/reader/USMappedColoradoGppReaderTest.java
  src/test/java/org/prebid/server/activity/infrastructure/privacy/usnat/reader/USMappedConnecticutGppReaderTest.java
  src/test/java/org/prebid/server/activity/infrastructure/privacy/usnat/reader/USMappedUtahGppReaderTest.java
  src/test/java/org/prebid/server/activity/infrastructure/privacy/usnat/reader/USMappedVirginiaGppReaderTest.java
  src/test/java/org/prebid/server/activity/infrastructure/privacy/usnat/reader/USNationalGppReaderTest.java
Labels: do not port

#3838 New Adapter: OrangeClickMedia - Limelight Alias
  src/main/resources/bidder-config/limelightDigital.yaml
  src/test/java/org/prebid/server/orangeclickmedia/OrangeClickMediaTest.java
  src/test/resources/org/prebid/server/it/openrtb2/orangeclickmedia/test-auction-orangeclickmedia-request.json
  src/test/resources/org/prebid/server/it/openrtb2/orangeclickmedia/test-auction-orangeclickmedia-response.json
  src/test/resources/org/prebid/server/it/openrtb2/orangeclickmedia/test-orangeclickmedia-bid-request.json
  src/test/resources/org/prebid/server/it/openrtb2/orangeclickmedia/test-orangeclickmedia-bid-response.json
  src/test/resources/org/prebid/server/it/test-application.properties
Labels: do not port

#3839 Aidem: Support only banner and video formats
  src/main/java/org/prebid/server/bidder/aidem/AidemBidder.java
  src/main/resources/bidder-config/aidem.yaml
  src/main/resources/static/bidder-params/aidem.json
  src/test/java/org/prebid/server/bidder/aidem/AidemBidderTest.java
Labels: do not port

#3867 Enforce Random Bid Id Feature
  docs/config-app.md
  src/main/java/org/prebid/server/auction/BidResponseCreator.java
  src/main/java/org/prebid/server/spring/config/ServiceConfiguration.java
  src/test/groovy/org/prebid/server/functional/tests/AuctionSpec.groovy
  src/test/groovy/org/prebid/server/functional/util/PBSUtils.groovy
  src/test/java/org/prebid/server/auction/BidResponseCreatorTest.java
Labels: do not port

#3874 New Adapter: AdmaticDe - Admatic alias
  src/main/resources/bidder-config/admatic.yaml
  src/test/java/org/prebid/server/it/AdmaticDeTest.java
  src/test/resources/org/prebid/server/it/openrtb2/admaticde/test-admaticde-bid-request.json
  src/test/resources/org/prebid/server/it/openrtb2/admaticde/test-admaticde-bid-response.json
  src/test/resources/org/prebid/server/it/openrtb2/admaticde/test-auction-admaticde-request.json
  src/test/resources/org/prebid/server/it/openrtb2/admaticde/test-auction-admaticde-response.json
  src/test/resources/org/prebid/server/it/test-application.properties
Labels: do not port

#3872 New Adapter: Pixad - Admatic alias
  src/main/resources/bidder-config/admatic.yaml
  src/test/java/org/prebid/server/it/PixadTest.java
  src/test/resources/org/prebid/server/it/openrtb2/pixad/test-auction-pixad-request.json
  src/test/resources/org/prebid/server/it/openrtb2/pixad/test-auction-pixad-response.json
  src/test/resources/org/prebid/server/it/openrtb2/pixad/test-pixad-bid-request.json
  src/test/resources/org/prebid/server/it/openrtb2/pixad/test-pixad-bid-response.json
  src/test/resources/org/prebid/server/it/test-application.properties
Labels: do not port

#3788 Ogury: port new adapter from Go
  src/main/java/org/prebid/server/bidder/ogury/OguryBidder.java
  src/main/java/org/prebid/server/spring/config/bidder/OguryConfiguration.java
  src/main/resources/bidder-config/ogury.yaml
  src/main/resources/static/bidder-params/ogury.json
  src/test/java/org/prebid/server/bidder/ogury/OguryBidderTest.java
  src/test/java/org/prebid/server/it/OguryTest.java
  src/test/resources/org/prebid/server/it/openrtb2/ogury/test-auction-ogury-request.json
  src/test/resources/org/prebid/server/it/openrtb2/ogury/test-auction-ogury-response.json
  src/test/resources/org/prebid/server/it/openrtb2/ogury/test-ogury-bid-request.json
  src/test/resources/org/prebid/server/it/openrtb2/ogury/test-ogury-bid-response.json
  src/test/resources/org/prebid/server/it/test-application.properties
Labels: do not port

#3684 Kobler: New adapter ported from Go
  src/main/java/org/prebid/server/bidder/kobler/KoblerBidder.java
  src/main/java/org/prebid/server/proto/openrtb/ext/request/kobler/ExtImpKobler.java
  src/main/java/org/prebid/server/spring/config/bidder/KoblerConfiguration.java
  src/main/resources/bidder-config/kobler.yaml
  src/main/resources/static/bidder-params/kobler.json
  src/test/java/org/prebid/server/bidder/kobler/KoblerBidderTest.java
  src/test/java/org/prebid/server/it/KoblerTest.java
  src/test/resources/org/prebid/server/it/openrtb2/kobler/test-auction-kobler-request.json
  src/test/resources/org/prebid/server/it/openrtb2/kobler/test-auction-kobler-response.json
  src/test/resources/org/prebid/server/it/openrtb2/kobler/test-kobler-bid-request.json
  src/test/resources/org/prebid/server/it/openrtb2/kobler/test-kobler-bid-response.json
  src/test/resources/org/prebid/server/it/test-application.properties
Labels: do not port

#3866 Test: Multiple bidder codes
  src/test/groovy/org/prebid/server/functional/model/request/auction/AuctionEnvironment.groovy
  src/test/groovy/org/prebid/server/functional/tests/AlternateBidderCodeSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/BidAdjustmentSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/bidder/openx/OpenxSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsRulesSpec.groovy
Labels: tests

#3877 Port Smilewanted: change endpoint to HTTPS
  src/main/resources/bidder-config/smilewanted.yaml
Labels: do not port

#3876 Port Nextmillennium: Add gzip compression
  src/main/resources/bidder-config/nextmillennium.yaml
Labels: do not port

#3913 Port Improve Digital: Add iframe user sync
  src/main/resources/bidder-config/improvedigital.yaml
Labels: do not port

#3902 Modules execution plan: fix NPE
  src/main/java/org/prebid/server/hooks/execution/HookStageExecutor.java
  src/main/java/org/prebid/server/hooks/execution/model/ExecutionPlan.java
Labels: do not port

#3827 ResetDigital Adapter Update
  src/main/java/org/prebid/server/bidder/resetdigital/ResetDigitalBidder.java
  src/main/java/org/prebid/server/bidder/resetdigital/request/ResetDigitalImp.java
  src/main/java/org/prebid/server/bidder/resetdigital/request/ResetDigitalImpExt.java
  src/main/java/org/prebid/server/bidder/resetdigital/request/ResetDigitalImpMediaType.java
  src/main/java/org/prebid/server/bidder/resetdigital/request/ResetDigitalImpMediaTypes.java
  src/main/java/org/prebid/server/bidder/resetdigital/request/ResetDigitalImpZone.java
  src/main/java/org/prebid/server/bidder/resetdigital/request/ResetDigitalRequest.java
  src/main/java/org/prebid/server/bidder/resetdigital/request/ResetDigitalSite.java
  src/main/java/org/prebid/server/bidder/resetdigital/response/ResetDigitalBid.java
  src/main/java/org/prebid/server/bidder/resetdigital/response/ResetDigitalResponse.java
  src/main/java/org/prebid/server/spring/config/bidder/ResetDigitalConfiguration.java
  src/main/resources/bidder-config/resetdigital.yaml
  src/main/resources/static/bidder-params/resetdigital.json
  src/test/java/org/prebid/server/bidder/resetdigital/ResetDigitalBidderTest.java
  src/test/resources/org/prebid/server/it/openrtb2/resetdigital/test-auction-resetdigital-request.json
  src/test/resources/org/prebid/server/it/openrtb2/resetdigital/test-auction-resetdigital-response.json
  src/test/resources/org/prebid/server/it/openrtb2/resetdigital/test-resetdigital-bid-request.json
  src/test/resources/org/prebid/server/it/openrtb2/resetdigital/test-resetdigital-bid-response.json
Labels: do not port

#3869 Port FeedAd: New Adapter
  src/main/java/org/prebid/server/bidder/feedad/FeedAdBidder.java
  src/main/java/org/prebid/server/spring/config/bidder/FeedAdConfiguration.java
  src/main/resources/bidder-config/feedad.yaml
  src/main/resources/static/bidder-params/feedad.json
  src/test/java/org/prebid/server/bidder/feedad/FeedAdBidderTest.java
  src/test/java/org/prebid/server/it/FeedAdTest.java
  src/test/resources/org/prebid/server/it/openrtb2/feedad/test-auction-feedad-request.json
  src/test/resources/org/prebid/server/it/openrtb2/feedad/test-auction-feedad-response.json
  src/test/resources/org/prebid/server/it/openrtb2/feedad/test-feedad-bid-request.json
  src/test/resources/org/prebid/server/it/openrtb2/feedad/test-feedad-bid-response.json
  src/test/resources/org/prebid/server/it/test-application.properties
Labels: do not port

#3779 OMS: add video support
  src/main/java/org/prebid/server/bidder/oms/OmsBidder.java
  src/main/java/org/prebid/server/proto/openrtb/ext/request/omx/ExtImpOms.java
  src/main/resources/bidder-config/oms.yaml
  src/main/resources/static/bidder-params/oms.json
  src/test/java/org/prebid/server/bidder/oms/OmsBidderTest.java
  src/test/resources/org/prebid/server/it/openrtb2/oms/test-auction-oms-request.json
  src/test/resources/org/prebid/server/it/openrtb2/oms/test-auction-oms-response.json
  src/test/resources/org/prebid/server/it/openrtb2/oms/test-oms-bid-request.json
  src/test/resources/org/prebid/server/it/openrtb2/oms/test-oms-bid-response.json
Labels: do not port

#3907 Test: Fix flaky
  src/test/groovy/org/prebid/server/functional/tests/AuctionSpec.groovy
Labels: tests, do not port

#3926 Revert "ResetDigital Adapter Update (#3827)"
  src/main/java/org/prebid/server/bidder/resetdigital/ResetDigitalBidder.java
  src/main/java/org/prebid/server/bidder/resetdigital/request/ResetDigitalImp.java
  src/main/java/org/prebid/server/bidder/resetdigital/request/ResetDigitalImpExt.java
  src/main/java/org/prebid/server/bidder/resetdigital/request/ResetDigitalImpMediaType.java
  src/main/java/org/prebid/server/bidder/resetdigital/request/ResetDigitalImpMediaTypes.java
  src/main/java/org/prebid/server/bidder/resetdigital/request/ResetDigitalImpZone.java
  src/main/java/org/prebid/server/bidder/resetdigital/request/ResetDigitalRequest.java
  src/main/java/org/prebid/server/bidder/resetdigital/request/ResetDigitalSite.java
  src/main/java/org/prebid/server/bidder/resetdigital/response/ResetDigitalBid.java
  src/main/java/org/prebid/server/bidder/resetdigital/response/ResetDigitalResponse.java
  src/main/java/org/prebid/server/spring/config/bidder/ResetDigitalConfiguration.java
  src/main/resources/bidder-config/resetdigital.yaml
  src/main/resources/static/bidder-params/resetdigital.json
  src/test/java/org/prebid/server/bidder/resetdigital/ResetDigitalBidderTest.java
  src/test/resources/org/prebid/server/it/openrtb2/resetdigital/test-auction-resetdigital-request.json
  src/test/resources/org/prebid/server/it/openrtb2/resetdigital/test-auction-resetdigital-response.json
  src/test/resources/org/prebid/server/it/openrtb2/resetdigital/test-resetdigital-bid-request.json
  src/test/resources/org/prebid/server/it/openrtb2/resetdigital/test-resetdigital-bid-response.json
Labels: do not port

#3925 Tests: GPP decode error shouldn't fails entire auction
  src/test/groovy/org/prebid/server/functional/tests/privacy/GppSyncUserActivitiesSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/privacy/GppTransmitEidsActivitiesSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/privacy/GppTransmitUfpdActivitiesSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/privacy/PrivacyBaseSpec.groovy
Labels: tests

#3908 AppNexus: Support member param as int
  src/main/resources/static/bidder-params/appnexus.json
Labels: do not port

#3911 Smaato: Add iframe user sync
  src/main/resources/bidder-config/smaato.yaml
Labels: do not port

#3919 Algorix: Add site support
  src/main/resources/bidder-config/algorix.yaml
Labels: do not port

#3856 ImproveDigital: add iframe sync
  src/main/resources/bidder-config/improvedigital.yaml
Labels: do not port

#3848 Addigi: New alias for Smarthub
  src/main/resources/bidder-config/smarthub.yaml
  src/test/java/org/prebid/server/it/AddigiTest.java
  src/test/resources/org/prebid/server/it/openrtb2/addigi/test-addigi-bid-request.json
  src/test/resources/org/prebid/server/it/openrtb2/addigi/test-addigi-bid-response.json
  src/test/resources/org/prebid/server/it/openrtb2/addigi/test-auction-addigi-request.json
  src/test/resources/org/prebid/server/it/openrtb2/addigi/test-auction-addigi-response.json
  src/test/resources/org/prebid/server/it/test-application.properties
Labels: do not port

#3842 Add aws default credentials provider
  docs/application-settings.md
  docs/config-app.md
  src/main/java/org/prebid/server/spring/config/SettingsConfiguration.java
  src/test/java/org/prebid/server/hooks/execution/HookStageExecutorTest.java
Labels: do not port

#3840 New Adapter: Velonium - Limelight Alias
  src/main/resources/bidder-config/limelightDigital.yaml
  src/test/java/org/prebid/server/it/VeloniumTest.java
  src/test/resources/org/prebid/server/it/openrtb2/velonium/test-auction-velonium-request.json
  src/test/resources/org/prebid/server/it/openrtb2/velonium/test-auction-velonium-response.json
  src/test/resources/org/prebid/server/it/openrtb2/velonium/test-velonium-bid-request.json
  src/test/resources/org/prebid/server/it/openrtb2/velonium/test-velonium-bid-response.json
  src/test/resources/org/prebid/server/it/test-application.properties
Labels: do not port

#3932 Compare currencies ignoring case
  src/main/java/org/prebid/server/util/BidderUtil.java
  src/test/java/org/prebid/server/it/AdtgorgTest.java
  src/test/java/org/prebid/server/util/BidderUtilTest.java
Labels: do not port

#3906 Dependencies: Bump core component versions
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  extra/modules/fiftyone-devicedetection/pom.xml
  extra/modules/greenbids-real-time-data/pom.xml
  extra/pom.xml
  mvnw
  mvnw.cmd
  pom.xml
  src/test/groovy/org/prebid/server/functional/tests/BidderParamsSpec.groovy
Labels: do not port

#3928 Test: stored imp and stored request
  src/test/groovy/org/prebid/server/functional/model/bidder/AppNexus.groovy
  src/test/groovy/org/prebid/server/functional/tests/BidderParamsSpec.groovy
Labels: tests

#3741 Tests: Increase coverage for floors validation
  src/test/groovy/org/prebid/server/functional/tests/BaseSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/BidValidationSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/MetricsSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/bidder/openx/OpenxSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsBaseSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsFetchingSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsRulesSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsSignalingSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/privacy/GdprAmpSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/privacy/GdprAuctionSpec.groovy
Labels: tests

#3931 Fix Stored Request Merging
  src/main/java/org/prebid/server/json/JsonMerger.java
  src/main/java/org/prebid/server/json/merge/JsonMergePatch.java
  src/main/java/org/prebid/server/json/merge/JsonMergePatchDeserializer.java
  src/main/java/org/prebid/server/json/merge/NonObjectMergePatch.java
  src/main/java/org/prebid/server/json/merge/ObjectMergePatch.java
  src/test/groovy/org/prebid/server/functional/model/bidder/AppNexus.groovy
  src/test/groovy/org/prebid/server/functional/tests/BidderParamsSpec.groovy
  src/test/java/org/prebid/server/json/merge/JsonMergePatchTest.java
Labels: do not port

#3924 Price Floor Logs Update
  src/main/java/org/prebid/server/floors/BasicPriceFloorProcessor.java
  src/main/java/org/prebid/server/floors/PriceFloorFetcher.java
  src/main/java/org/prebid/server/floors/proto/FetchResult.java
  src/main/java/org/prebid/server/spring/config/PriceFloorsConfiguration.java
  src/test/groovy/org/prebid/server/functional/tests/BaseSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/BidValidationSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/MetricsSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/bidder/openx/OpenxSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsBaseSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsFetchingSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsRulesSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsSignalingSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/privacy/GdprAmpSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/privacy/GdprAuctionSpec.groovy
  src/test/java/org/prebid/server/floors/BasicPriceFloorProcessorTest.java
  src/test/java/org/prebid/server/floors/PriceFloorFetcherTest.java
Labels: do not port

#3943 Tests: fix alert.general metric conflict
  src/test/groovy/org/prebid/server/functional/model/privacy/Metric.groovy
  src/test/groovy/org/prebid/server/functional/tests/privacy/GppFetchBidActivitiesSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/privacy/GppSyncUserActivitiesSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/privacy/GppTransmitEidsActivitiesSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/privacy/GppTransmitPreciseGeoActivitiesSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/privacy/GppTransmitUfpdActivitiesSpec.groovy
Labels: tests, do not port
