Repository prebid/prebid-server-java, pull requests merged in 2025-05, with the labels that each got.

#3814 NextMillennium: Adapter and server version
  src/main/java/org/prebid/server/bidder/nextmillennium/NextMillenniumBidder.java
  src/main/java/org/prebid/server/bidder/nextmillennium/proto/NextMillenniumExt.java
  src/main/java/org/prebid/server/bidder/nextmillennium/proto/NextMillenniumExtBidder.java
  src/main/java/org/prebid/server/spring/config/bidder/NextMillenniumConfiguration.java
  src/test/java/org/prebid/server/bidder/nextmillennium/NextMillenniumBidderTest.java
  src/test/resources/org/prebid/server/it/openrtb2/nextmillennium/test-nextmillennium-bid-request.json
Labels: do not port

#3916 New Adapter: Seedtag
  src/main/java/org/prebid/server/bidder/seedtag/SeedtagBidder.java
  src/main/java/org/prebid/server/proto/openrtb/ext/request/seedtag/ExtImpSeedtag.java
  src/main/java/org/prebid/server/spring/config/bidder/SeedtagConfiguration.java
  src/main/resources/bidder-config/seedtag.yaml
  src/main/resources/static/bidder-params/seedtag.json
  src/test/java/org/prebid/server/bidder/seedtag/SeedtagBidderTest.java
  src/test/java/org/prebid/server/it/SeedtagTest.java
  src/test/resources/org/prebid/server/it/openrtb2/seedtag/test-auction-seedtag-request.json
  src/test/resources/org/prebid/server/it/openrtb2/seedtag/test-auction-seedtag-response.json
  src/test/resources/org/prebid/server/it/openrtb2/seedtag/test-seedtag-bid-request.json
  src/test/resources/org/prebid/server/it/openrtb2/seedtag/test-seedtag-bid-response.json
  src/test/resources/org/prebid/server/it/test-application.properties
Labels: do not port

#3949 Test: Rename `ModelGroup`
  src/test/groovy/org/prebid/server/functional/model/pricefloors/FloorModelGroup.groovy
  src/test/groovy/org/prebid/server/functional/model/pricefloors/PriceFloorData.groovy
  src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsFetchingSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsRulesSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsSignalingSpec.groovy
Labels: tests, do not port

#3951 Port TheTradeDesk: Dynamically construct endpoint using supplySourceId
  src/main/java/org/prebid/server/bidder/thetradedesk/TheTradeDeskBidder.java
  src/main/java/org/prebid/server/proto/openrtb/ext/request/thetradedesk/ExtImpTheTradeDesk.java
  src/main/resources/static/bidder-params/thetradedesk.json
  src/test/java/org/prebid/server/bidder/thetradedesk/TheTradeDeskBidderTest.java
  src/test/resources/org/prebid/server/it/openrtb2/thetradedesk/test-auction-thetradedesk-request.json
  src/test/resources/org/prebid/server/it/openrtb2/thetradedesk/test-thetradedesk-bid-request.json
  src/test/resources/org/prebid/server/it/test-application.properties
Labels: do not port

#3956 InvibesBidder: fix parameter parsing issue
  src/main/java/org/prebid/server/bidder/invibes/InvibesBidder.java
  src/test/java/org/prebid/server/bidder/invibes/InvibesBidderTest.java
Labels: do not port

#3952 Tests: Increase coverage for floors logs tests
  src/test/groovy/org/prebid/server/functional/model/privacy/Metric.groovy
  src/test/groovy/org/prebid/server/functional/model/response/auction/Bid.groovy
  src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsBaseSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsFetchingSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsSignalingSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/privacy/GppFetchBidActivitiesSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/privacy/GppSyncUserActivitiesSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/privacy/GppTransmitEidsActivitiesSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/privacy/GppTransmitPreciseGeoActivitiesSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/privacy/GppTransmitUfpdActivitiesSpec.groovy
Labels: tests

#3865 Zeta Global SSP: Add sid parameter and audio support, no longer generic
  src/main/java/org/prebid/server/bidder/zeta_global_ssp/ZetaGlobalSspBidder.java
  src/main/java/org/prebid/server/proto/openrtb/ext/request/zeta_global_ssp/ExtImpZetaGlobalSSP.java
  src/main/java/org/prebid/server/spring/config/bidder/ZetaGlobalSspConfiguration.java
  src/main/resources/bidder-config/generic.yaml
  src/main/resources/bidder-config/zeta_global_ssp.yaml
  src/main/resources/static/bidder-params/zeta_global_ssp.json
  src/test/java/org/prebid/server/bidder/zeta_global_ssp/ZetaGlobalSspBidderTest.java
  src/test/resources/org/prebid/server/it/openrtb2/zeta_global_ssp/test-auction-zeta_global_ssp-request.json
  src/test/resources/org/prebid/server/it/openrtb2/zeta_global_ssp/test-zeta_global_ssp-bid-request.json
  src/test/resources/org/prebid/server/it/openrtb2/zeta_global_ssp/test-zeta_global_ssp-bid-response.json
  src/test/resources/org/prebid/server/it/test-application.properties
Labels: do not port

#3958 Test: Invalid GPP string for request handling
  src/test/groovy/org/prebid/server/functional/tests/privacy/GppSyncUserActivitiesSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/privacy/GppTransmitEidsActivitiesSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/privacy/GppTransmitUfpdActivitiesSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/privacy/PrivacyBaseSpec.groovy
Labels: tests

#3880 Epsilon: native support
  src/main/java/org/prebid/server/bidder/epsilon/EpsilonBidder.java
  src/main/resources/bidder-config/epsilon.yaml
  src/test/java/org/prebid/server/bidder/epsilon/EpsilonBidderTest.java
Labels: do not port

#3954 Dependencies: Change spring-boot version
  extra/pom.xml
Labels: dependencies, do not port

#3950 Price Floor Logs Update
  src/main/java/org/prebid/server/floors/BasicPriceFloorProcessor.java
  src/main/java/org/prebid/server/floors/PriceFloorFetcher.java
  src/main/java/org/prebid/server/floors/proto/FetchResult.java
  src/main/java/org/prebid/server/spring/config/PriceFloorsConfiguration.java
  src/test/groovy/org/prebid/server/functional/model/privacy/Metric.groovy
  src/test/groovy/org/prebid/server/functional/model/response/auction/Bid.groovy
  src/test/groovy/org/prebid/server/functional/tests/BaseSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/BidValidationSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/MetricsSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/bidder/openx/OpenxSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsBaseSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsFetchingSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsRulesSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsSignalingSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/privacy/GdprAmpSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/privacy/GdprAuctionSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/privacy/GppFetchBidActivitiesSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/privacy/GppSyncUserActivitiesSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/privacy/GppTransmitEidsActivitiesSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/privacy/GppTransmitPreciseGeoActivitiesSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/privacy/GppTransmitUfpdActivitiesSpec.groovy
  src/test/java/org/prebid/server/floors/BasicPriceFloorProcessorTest.java
  src/test/java/org/prebid/server/floors/PriceFloorFetcherTest.java
Labels: do not port

#3961 ActivityInfrastructure: Add exception handling
  src/main/java/org/prebid/server/activity/infrastructure/creator/ActivityInfrastructureCreator.java
  src/main/java/org/prebid/server/activity/infrastructure/creator/privacy/uscustomlogic/USCustomLogicModuleCreator.java
  src/main/java/org/prebid/server/activity/infrastructure/creator/privacy/usnat/USNatModuleCreator.java
  src/main/java/org/prebid/server/activity/infrastructure/creator/rule/PrivacyModulesRuleCreator.java
  src/main/java/org/prebid/server/spring/config/ActivityInfrastructureConfiguration.java
  src/test/groovy/org/prebid/server/functional/tests/privacy/GppSyncUserActivitiesSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/privacy/GppTransmitEidsActivitiesSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/privacy/GppTransmitUfpdActivitiesSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/privacy/PrivacyBaseSpec.groovy
  src/test/java/org/prebid/server/activity/infrastructure/creator/ActivityInfrastructureCreatorTest.java
  src/test/java/org/prebid/server/activity/infrastructure/creator/privacy/uscustomlogic/USCustomLogicModuleCreatorTest.java
  src/test/java/org/prebid/server/activity/infrastructure/creator/privacy/usnat/USNatModuleCreatorTest.java
  src/test/java/org/prebid/server/activity/infrastructure/creator/rule/PrivacyModulesRuleCreatorTest.java
Labels: do not port

#3966 Revert "Zeta Global SSP bidder port
  src/main/java/org/prebid/server/bidder/zeta_global_ssp/ZetaGlobalSspBidder.java
  src/main/java/org/prebid/server/proto/openrtb/ext/request/zeta_global_ssp/ExtImpZetaGlobalSSP.java
  src/main/java/org/prebid/server/spring/config/bidder/ZetaGlobalSspConfiguration.java
  src/main/resources/bidder-config/generic.yaml
  src/main/resources/bidder-config/zeta_global_ssp.yaml
  src/main/resources/static/bidder-params/zeta_global_ssp.json
  src/test/java/org/prebid/server/bidder/zeta_global_ssp/ZetaGlobalSspBidderTest.java
  src/test/resources/org/prebid/server/it/openrtb2/zeta_global_ssp/test-auction-zeta_global_ssp-request.json
  src/test/resources/org/prebid/server/it/openrtb2/zeta_global_ssp/test-zeta_global_ssp-bid-request.json
  src/test/resources/org/prebid/server/it/openrtb2/zeta_global_ssp/test-zeta_global_ssp-bid-response.json
  src/test/resources/org/prebid/server/it/test-application.properties
Labels: do not port

#3968 Revert "Dependencies: Change spring-boot version (#3954)"
  extra/pom.xml
Labels: dependencies, do not port

#3903 Test: Bid rounding
  src/test/groovy/org/prebid/server/functional/model/config/AccountAuctionConfig.groovy
  src/test/groovy/org/prebid/server/functional/model/request/auction/BidRounding.groovy
  src/test/groovy/org/prebid/server/functional/tests/AmpSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/BaseSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/BidRoundingSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsEnforcementSpec.groovy
Labels: tests

#3868 Tests: adjust floors for bidadjustments
  src/test/groovy/org/prebid/server/functional/model/request/auction/BidAdjustmentRule.groovy
  src/test/groovy/org/prebid/server/functional/model/request/auction/BidRequest.groovy
  src/test/groovy/org/prebid/server/functional/model/response/auction/Bid.groovy
  src/test/groovy/org/prebid/server/functional/model/response/auction/BidMediaType.groovy
  src/test/groovy/org/prebid/server/functional/tests/BaseSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/BidAdjustmentSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsAdjustmentSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsBaseSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsCurrencySpec.groovy
Labels: tests
