Repository prebid/prebid-server-java, pull requests merged in 2025-03, with the labels that each got.

#3732 Admatic: Update headers for adapter
  src/main/java/org/prebid/server/bidder/admatic/AdmaticBidder.java
  src/test/java/org/prebid/server/bidder/admatic/AdmaticBidderTest.java
Labels: do not port

#3773 NextMillennium: Adapter and server version
  src/main/java/org/prebid/server/bidder/nextmillennium/NextMillenniumBidder.java
  src/main/java/org/prebid/server/spring/config/bidder/NextMillenniumConfiguration.java
  src/test/java/org/prebid/server/bidder/nextmillennium/NextMillenniumBidderTest.java
  src/test/resources/org/prebid/server/it/openrtb2/nextmillennium/test-nextmillennium-bid-request.json
Labels: do not port

#3775 Copper6SSP: Fix endpoint
  src/main/resources/bidder-config/copper6ssp.yaml
Labels: do not port

#3776 Pubrise: Fix endpoint
  src/main/resources/bidder-config/pubrise.yaml
Labels: do not port

#3777 sspBC: Endpoint update
  src/main/resources/bidder-config/sspbc.yaml
Labels: do not port

#3778 Adt: port new alias of Admatic from Go
  src/main/resources/bidder-config/admatic.yaml
  src/test/java/org/prebid/server/it/AdtTest.java
  src/test/resources/org/prebid/server/it/openrtb2/adt/test-adt-bid-request.json
  src/test/resources/org/prebid/server/it/openrtb2/adt/test-adt-bid-response.json
  src/test/resources/org/prebid/server/it/openrtb2/adt/test-auction-adt-request.json
  src/test/resources/org/prebid/server/it/openrtb2/adt/test-auction-adt-response.json
  src/test/resources/org/prebid/server/it/test-application.properties
Labels: do not port

#3795 Artechnology: port new alias of StartHub from Go
  src/main/resources/bidder-config/smarthub.yaml
  src/test/java/org/prebid/server/it/ArtechnologyTest.java
  src/test/resources/org/prebid/server/it/openrtb2/artechnology/test-artechnology-bid-request.json
  src/test/resources/org/prebid/server/it/openrtb2/artechnology/test-artechnology-bid-response.json
  src/test/resources/org/prebid/server/it/openrtb2/artechnology/test-auction-artechnology-request.json
  src/test/resources/org/prebid/server/it/openrtb2/artechnology/test-auction-artechnology-response.json
  src/test/resources/org/prebid/server/it/test-application.properties
Labels: do not port

#3794 Adinify: port new alias of StartHub from Go
  src/main/resources/bidder-config/smarthub.yaml
  src/test/java/org/prebid/server/it/AdinifyTest.java
  src/test/resources/org/prebid/server/it/openrtb2/adinify/test-adinify-bid-request.json
  src/test/resources/org/prebid/server/it/openrtb2/adinify/test-adinify-bid-response.json
  src/test/resources/org/prebid/server/it/openrtb2/adinify/test-auction-adinify-request.json
  src/test/resources/org/prebid/server/it/openrtb2/adinify/test-auction-adinify-response.json
  src/test/resources/org/prebid/server/it/test-application.properties
Labels: do not port

#3792 Jambojar: port new alias of StartHub from Go
  src/main/resources/bidder-config/smarthub.yaml
  src/test/java/org/prebid/server/it/JambojarTest.java
  src/test/resources/org/prebid/server/it/openrtb2/jambojar/test-auction-jambojar-request.json
  src/test/resources/org/prebid/server/it/openrtb2/jambojar/test-auction-jambojar-response.json
  src/test/resources/org/prebid/server/it/openrtb2/jambojar/test-jambojar-bid-request.json
  src/test/resources/org/prebid/server/it/openrtb2/jambojar/test-jambojar-bid-response.json
  src/test/resources/org/prebid/server/it/test-application.properties
Labels: do not port

#3791 Rubicon Adapter: pass bid request ID to XAPI
  src/main/java/org/prebid/server/bidder/rubicon/RubiconBidder.java
  src/main/java/org/prebid/server/bidder/rubicon/proto/request/RubiconImpExtRp.java
  src/main/java/org/prebid/server/spring/config/bidder/RubiconConfiguration.java
  src/main/resources/bidder-config/rubicon.yaml
  src/test/java/org/prebid/server/bidder/rubicon/RubiconBidderTest.java
  src/test/java/org/prebid/server/it/MagniteTest.java
  src/test/java/org/prebid/server/it/RubiconTest.java
  src/test/java/org/prebid/server/it/hooks/HooksTest.java
  src/test/resources/org/prebid/server/it/hooks/reject/test-auction-bidder-request-reject-request.json
  src/test/resources/org/prebid/server/it/hooks/reject/test-auction-bidder-request-reject-response.json
  src/test/resources/org/prebid/server/it/hooks/reject/test-auction-processed-auction-request-reject-request.json
  src/test/resources/org/prebid/server/it/hooks/reject/test-auction-processed-bidder-response-reject-request.json
  src/test/resources/org/prebid/server/it/hooks/reject/test-auction-processed-bidder-response-reject-response.json
  src/test/resources/org/prebid/server/it/hooks/reject/test-auction-raw-auction-request-reject-request.json
  src/test/resources/org/prebid/server/it/hooks/reject/test-auction-raw-bidder-response-reject-request.json
  src/test/resources/org/prebid/server/it/hooks/reject/test-auction-raw-bidder-response-reject-response.json
  src/test/resources/org/prebid/server/it/hooks/reject/test-generic-bid-request.json
  src/test/resources/org/prebid/server/it/hooks/reject/test-generic-bid-response.json
  src/test/resources/org/prebid/server/it/hooks/reject/test-rubicon-bid-request-1.json
  src/test/resources/org/prebid/server/it/hooks/sample-module/test-auction-generic-request.json
  src/test/resources/org/prebid/server/it/hooks/sample-module/test-auction-generic-response.json
  src/test/resources/org/prebid/server/it/hooks/sample-module/test-generic-bid-request.json
  src/test/resources/org/prebid/server/it/hooks/sample-module/test-generic-bid-response.json
  src/test/resources/org/prebid/server/it/hooks/sample-module/test-rubicon-bid-request-1.json
  src/test/resources/org/prebid/server/it/openrtb2/magnite/test-auction-magnite-response.json
  src/test/resources/org/prebid/server/it/openrtb2/magnite/test-magnite-bid-request.json
  src/test/resources/org/prebid/server/it/openrtb2/rubicon/test-rubicon-bid-request.json
Labels: do not port

#3768 Docs: Create a Doc with Guidance for Porting from Go
  docs/developers/bid-adapter-porting-guide.md
Labels: do not port

#3807 Tests: Fix Maven build issue with IAB Tech Lab's Protobuf
  .github/workflows/pr-java-ci.yml
  src/test/proto/test-opernrtb.proto
Labels: do not port

#3786 Housekeeping: Update 3rd party dependencies
  extra/modules/greenbids-real-time-data/pom.xml
  extra/pom.xml
  src/test/groovy/org/prebid/server/functional/tests/AliasSpec.groovy
  src/test/java/org/prebid/server/geolocation/MaxMindGeoLocationServiceTest.java
  src/test/java/org/prebid/server/validation/BidderParamValidatorTest.java
Labels: dependencies, do not port

#3806 Vidazoo: Declare OpenRTB 2.6 support
  src/main/resources/bidder-config/vidazoo.yaml
  src/test/resources/org/prebid/server/it/openrtb2/vidazoo/test-auction-vidazoo-request.json
  src/test/resources/org/prebid/server/it/openrtb2/vidazoo/test-vidazoo-bid-request.json
Labels: do not port

#3793 Dependencies: resolve maven conflicts between core and bundle
  extra/modules/greenbids-real-time-data/pom.xml
Labels: dependencies

#3805 New Adapter: Streamvision - LimelightDigital Alias
  src/main/resources/bidder-config/limelightDigital.yaml
  src/test/java/org/prebid/server/it/StreamvisionTest.java
  src/test/resources/org/prebid/server/it/openrtb2/streamvision/test-auction-streamvision-request.json
  src/test/resources/org/prebid/server/it/openrtb2/streamvision/test-auction-streamvision-response.json
  src/test/resources/org/prebid/server/it/openrtb2/streamvision/test-streamvision-bid-request.json
  src/test/resources/org/prebid/server/it/openrtb2/streamvision/test-streamvision-bid-response.json
  src/test/resources/org/prebid/server/it/test-application.properties
Labels: do not port

#3705 Adverxo: New adapter ported from Go
  src/main/java/org/prebid/server/bidder/adverxo/AdverxoBidder.java
  src/main/java/org/prebid/server/proto/openrtb/ext/request/adverxo/ExtImpAdverxo.java
  src/main/java/org/prebid/server/spring/config/bidder/AdverxoBidderConfiguration.java
  src/main/resources/bidder-config/adverxo.yaml
  src/main/resources/static/bidder-params/adverxo.json
  src/test/java/org/prebid/server/bidder/adverxo/AdverxoBidderTest.java
  src/test/java/org/prebid/server/it/AdportTest.java
  src/test/java/org/prebid/server/it/AdverxoTest.java
  src/test/java/org/prebid/server/it/BidsmindTest.java
  src/test/java/org/prebid/server/it/MobuppsTest.java
  src/test/resources/org/prebid/server/it/openrtb2/adport/test-adport-bid-request.json
  src/test/resources/org/prebid/server/it/openrtb2/adport/test-adport-bid-response.json
  src/test/resources/org/prebid/server/it/openrtb2/adport/test-auction-adport-request.json
  src/test/resources/org/prebid/server/it/openrtb2/adport/test-auction-adport-response.json
  src/test/resources/org/prebid/server/it/openrtb2/adverxo/test-adverxo-bid-request.json
  src/test/resources/org/prebid/server/it/openrtb2/adverxo/test-adverxo-bid-response.json
  src/test/resources/org/prebid/server/it/openrtb2/adverxo/test-auction-adverxo-request.json
  src/test/resources/org/prebid/server/it/openrtb2/adverxo/test-auction-adverxo-response.json
  src/test/resources/org/prebid/server/it/openrtb2/bidsmind/test-auction-bidsmind-request.json
  src/test/resources/org/prebid/server/it/openrtb2/bidsmind/test-auction-bidsmind-response.json
  src/test/resources/org/prebid/server/it/openrtb2/bidsmind/test-bidsmind-bid-request.json
  src/test/resources/org/prebid/server/it/openrtb2/bidsmind/test-bidsmind-bid-response.json
  src/test/resources/org/prebid/server/it/openrtb2/mobupps/test-auction-mobupps-request.json
  src/test/resources/org/prebid/server/it/openrtb2/mobupps/test-auction-mobupps-response.json
  src/test/resources/org/prebid/server/it/openrtb2/mobupps/test-mobupps-bid-request.json
  src/test/resources/org/prebid/server/it/openrtb2/mobupps/test-mobupps-bid-response.json
  src/test/resources/org/prebid/server/it/test-application.properties
Labels: do not port

#3781 Connatix: Port adapter from PBS-Go
  src/main/java/org/prebid/server/bidder/connatix/ConnatixBidder.java
  src/main/java/org/prebid/server/proto/openrtb/ext/request/connatix/ExtImpConnatix.java
  src/main/java/org/prebid/server/spring/config/bidder/ConnatixConfiguration.java
  src/main/resources/bidder-config/connatix.yaml
  src/main/resources/static/bidder-params/connatix.json
  src/test/java/org/prebid/server/bidder/connatix/ConnatixBidderTest.java
  src/test/java/org/prebid/server/it/ConnatixTest.java
  src/test/resources/org/prebid/server/it/openrtb2/connatix/test-banner-auction-connatix-request.json
  src/test/resources/org/prebid/server/it/openrtb2/connatix/test-banner-auction-connatix-response.json
  src/test/resources/org/prebid/server/it/openrtb2/connatix/test-banner-connatix-bid-request.json
  src/test/resources/org/prebid/server/it/openrtb2/connatix/test-banner-connatix-bid-response.json
  src/test/resources/org/prebid/server/it/test-application.properties
Labels: do not port

#3847 Docker: Update base Docker image version
  Dockerfile
  Dockerfile-modules
Labels: dependencies, do not port

#3850 Test:Multiple bidder codes
  src/test/groovy/org/prebid/server/functional/tests/AlternateBidderCodeSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/BidAdjustmentSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/BidderParamsSpec.groovy
Labels: tests

#3849 Multiple Bidder Codes Fix
  src/main/java/org/prebid/server/auction/BidResponseCreator.java
  src/main/java/org/prebid/server/auction/ExchangeService.java
  src/main/java/org/prebid/server/auction/aliases/BidderAliases.java
  src/main/java/org/prebid/server/auction/model/BidderResponseInfo.java
  src/main/java/org/prebid/server/bidadjustments/BidAdjustmentsProcessor.java
  src/main/java/org/prebid/server/validation/RequestValidator.java
  src/test/groovy/org/prebid/server/functional/tests/AlternateBidderCodeSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/BidAdjustmentSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/BidderParamsSpec.groovy
  src/test/java/org/prebid/server/auction/BidResponseCreatorTest.java
  src/test/java/org/prebid/server/auction/ExchangeServiceTest.java
  src/test/java/org/prebid/server/auction/aliases/BidderAliasesTest.java
  src/test/java/org/prebid/server/bidadjustments/BidAdjustmentsProcessorTest.java
  src/test/java/org/prebid/server/validation/RequestValidatorTest.java
Labels: do not port

#3879 Tests: Enforce Random Bid Id Feature
  src/test/groovy/org/prebid/server/functional/tests/AuctionSpec.groovy
  src/test/groovy/org/prebid/server/functional/util/PBSUtils.groovy
Labels: tests
