Repository prebid/prebid-server-java, pull requests merged in 2025-02, with the labels that each got.

#3699 SmartHub: update to Attekmi
  src/main/resources/bidder-config/smarthub.yaml
  src/main/resources/static/bidder-params/smarthub.json
Labels: do not port

#3714 Criteo Bidder: Add pubid/uid fields
  src/main/resources/static/bidder-params/criteo.json
  src/test/resources/org/prebid/server/it/openrtb2/criteo/test-auction-criteo-request.json
  src/test/resources/org/prebid/server/it/openrtb2/criteo/test-criteo-bid-request.json
Labels: do not port

#3721 Vrtcal Bidder: ORTB 2.6 support
  src/main/resources/bidder-config/vrtcal.yaml
  src/test/resources/org/prebid/server/it/openrtb2/vrtcal/test-auction-vrtcal-request.json
  src/test/resources/org/prebid/server/it/openrtb2/vrtcal/test-vrtcal-bid-request.json
Labels: do not port

#3724 Insticator: fix video validation logic
  src/main/java/org/prebid/server/bidder/insticator/InsticatorBidder.java
  src/test/java/org/prebid/server/bidder/insticator/InsticatorBidderTest.java
Labels: do not port

#3722 Tests: Support testing the USGen privacy module
  src/test/groovy/org/prebid/server/functional/model/config/AccountGppConfig.groovy
  src/test/groovy/org/prebid/server/functional/model/response/auction/ActivityInfrastructure.groovy
  src/test/groovy/org/prebid/server/functional/model/response/auction/And.groovy
  src/test/groovy/org/prebid/server/functional/model/response/auction/RuleResult.groovy
  src/test/groovy/org/prebid/server/functional/tests/privacy/ActivityTraceLogSpec.groovy
Labels: tests

#3720 Yieldlab Bidder: Forward consent under param gdpr_consent
  src/main/java/org/prebid/server/bidder/yieldlab/YieldlabBidder.java
  src/main/java/org/prebid/server/bidder/yieldlab/model/YieldlabBid.java
  src/main/java/org/prebid/server/bidder/yieldlab/model/YieldlabDigitalServicesActResponse.java
  src/test/java/org/prebid/server/bidder/yieldlab/YieldlabBidderTest.java
Labels: do not port

#3650 Fix #3592. Bad Input Error if pbjs s2s config contains alias configuration for a disabled adapter
  docs/config-app.md
  docs/metrics.md
  src/main/java/org/prebid/server/auction/requestfactory/AmpRequestFactory.java
  src/main/java/org/prebid/server/auction/requestfactory/AuctionRequestFactory.java
  src/main/java/org/prebid/server/auction/requestfactory/Ortb2RequestFactory.java
  src/main/java/org/prebid/server/auction/requestfactory/VideoRequestFactory.java
  src/main/java/org/prebid/server/metric/MetricName.java
  src/main/java/org/prebid/server/metric/Metrics.java
  src/main/java/org/prebid/server/spring/config/ServiceConfiguration.java
  src/main/java/org/prebid/server/validation/RequestValidator.java
  src/main/resources/application.yaml
  src/test/java/org/prebid/server/auction/requestfactory/AmpRequestFactoryTest.java
  src/test/java/org/prebid/server/auction/requestfactory/AuctionRequestFactoryTest.java
  src/test/java/org/prebid/server/auction/requestfactory/Ortb2RequestFactoryTest.java
  src/test/java/org/prebid/server/auction/requestfactory/VideoRequestFactoryTest.java
  src/test/java/org/prebid/server/metric/MetricsTest.java
  src/test/java/org/prebid/server/validation/RequestValidatorTest.java
Labels: needs community

#3733 Blue: Add placementId bidder param #3609
  src/main/resources/static/bidder-params/blue.json
  src/test/java/org/prebid/server/it/BlueTest.java
  src/test/resources/org/prebid/server/it/openrtb2/blue/test-auction-blue-request.json
  src/test/resources/org/prebid/server/it/openrtb2/blue/test-auction-blue-response.json
  src/test/resources/org/prebid/server/it/openrtb2/blue/test-blue-bid-request.json
  src/test/resources/org/prebid/server/it/openrtb2/blue/test-blue-bid-response.json
  src/test/resources/org/prebid/server/it/test-application.properties
Labels: do not port

#3737 Compass: Add user sync GPP support #3734
  src/main/resources/bidder-config/compass.yaml
Labels: do not port

#3740 Adnuntius: Copy advertiserDomains to ORTB bid response adomain #3736
  src/main/java/org/prebid/server/bidder/adnuntius/AdnuntiusBidder.java
  src/main/java/org/prebid/server/bidder/adnuntius/model/response/AdnuntiusAd.java
  src/test/java/org/prebid/server/bidder/adnuntius/AdnuntiusBidderTest.java
  src/test/resources/org/prebid/server/it/openrtb2/adnuntius/test-adnuntius-bid-response.json
Labels: do not port

#3739 Use a hard-alias schema if present
  src/main/java/org/prebid/server/validation/BidderParamValidator.java
  src/test/java/org/prebid/server/bidder/adtrgtme/AdtrgtmeBidderTest.java
  src/test/java/org/prebid/server/it/ApplicationTest.java
  src/test/java/org/prebid/server/validation/BidderParamValidatorTest.java
Labels: do not port

#3759 Test: hard-alias schema
  src/test/groovy/org/prebid/server/functional/model/request/auction/Adrino.groovy
  src/test/groovy/org/prebid/server/functional/model/request/auction/Bidder.groovy
  src/test/groovy/org/prebid/server/functional/testcontainers/PbsConfig.groovy
  src/test/groovy/org/prebid/server/functional/tests/BidderParamsSpec.groovy
Labels: tests

#3755 RTB House: declare oRTB 2.6 support
  src/main/resources/bidder-config/rtbhouse.yaml
  src/test/resources/org/prebid/server/it/openrtb2/rtbhouse/test-auction-rtbhouse-request.json
  src/test/resources/org/prebid/server/it/openrtb2/rtbhouse/test-rtbhouse-bid-request.json
Labels: do not port

#3763 Functional tests for prebid cache traceability
  src/test/groovy/org/prebid/server/functional/model/request/cache/BidCachePut.groovy
  src/test/groovy/org/prebid/server/functional/tests/CacheSpec.groovy
Labels: tests

#3738 New adapter: Connektai - Xeworks alias #3730
  src/main/resources/bidder-config/xeworks.yaml
  src/test/java/org/prebid/server/it/ConnektaiTest.java
  src/test/resources/org/prebid/server/it/openrtb2/connektai/test-auction-connektai-request.json
  src/test/resources/org/prebid/server/it/openrtb2/connektai/test-auction-connektai-response.json
  src/test/resources/org/prebid/server/it/openrtb2/connektai/test-connektai-bid-request.json
  src/test/resources/org/prebid/server/it/openrtb2/connektai/test-connektai-bid-response.json
  src/test/resources/org/prebid/server/it/test-application.properties
Labels: do not port

#3774 Docs: documentation for Prebid Cache traceability improvements
  docs/config-app.md
  docs/metrics.md
Labels: do not port

#3780 Test: `allowPersonalDataConsent2` option to USGen module
  src/test/groovy/org/prebid/server/functional/model/config/GppModuleConfig.groovy
  src/test/groovy/org/prebid/server/functional/tests/privacy/GppFetchBidActivitiesSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/privacy/GppSyncUserActivitiesSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/privacy/GppTransmitEidsActivitiesSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/privacy/GppTransmitPreciseGeoActivitiesSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/privacy/GppTransmitUfpdActivitiesSpec.groovy
Labels: tests
