Repository prebid/prebid-server-java, pull requests merged in 2025-06, with the labels that each got.

#3930 Port Kueez: New Adapter
  src/main/java/org/prebid/server/bidder/kueezrtb/KueezRtbBidder.java
  src/main/java/org/prebid/server/proto/openrtb/ext/request/kueezrtb/KueezRtbImpExt.java
  src/main/java/org/prebid/server/spring/config/bidder/KueezRtbConfiguration.java
  src/main/resources/bidder-config/kueezrtb.yaml
  src/main/resources/static/bidder-params/kueezrtb.json
  src/test/groovy/org/prebid/server/functional/model/response/biddersparams/BidderParams.groovy
  src/test/java/org/prebid/server/bidder/kueezrtb/KueezRtbBidderTest.java
  src/test/java/org/prebid/server/it/KueezRtbTest.java
  src/test/resources/org/prebid/server/it/openrtb2/kueezrtb/test-auction-kueezrtb-request.json
  src/test/resources/org/prebid/server/it/openrtb2/kueezrtb/test-auction-kueezrtb-response.json
  src/test/resources/org/prebid/server/it/openrtb2/kueezrtb/test-kueezrtb-bid-request.json
  src/test/resources/org/prebid/server/it/openrtb2/kueezrtb/test-kueezrtb-bid-response.json
  src/test/resources/org/prebid/server/it/test-application.properties
Labels: do not port

#3969 Сriteo: ortb 2.6 support
  src/main/resources/bidder-config/criteo.yaml
  src/test/resources/org/prebid/server/it/openrtb2/criteo/test-criteo-bid-request.json
Labels: do not port

#3982 Functional tests/currency mock
  src/test/groovy/org/prebid/server/functional/service/PrebidServerService.groovy
  src/test/groovy/org/prebid/server/functional/testcontainers/PbsConfig.groovy
  src/test/groovy/org/prebid/server/functional/testcontainers/scaffolding/CurrencyConversion.groovy
  src/test/groovy/org/prebid/server/functional/tests/BidAdjustmentSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/CurrencySpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/StoredResponseSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsAdjustmentSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsBaseSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsCurrencySpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsSignalingSpec.groovy
  src/test/groovy/org/prebid/server/functional/util/CurrencyUtil.groovy
Labels: tests

#3939 Bid adjustments rules matching strategy
  src/main/java/org/prebid/server/bidadjustments/BidAdjustmentsProcessor.java
  src/main/java/org/prebid/server/bidadjustments/BidAdjustmentsResolver.java
  src/main/java/org/prebid/server/bidadjustments/BidAdjustmentsRulesResolver.java
  src/main/java/org/prebid/server/bidadjustments/FloorAdjustmentsResolver.java
  src/main/java/org/prebid/server/bidadjustments/model/BidAdjustmentsRules.java
  src/main/java/org/prebid/server/util/dsl/config/impl/MostAccurateCombinationStrategy.java
  src/test/groovy/org/prebid/server/functional/model/request/auction/BidAdjustmentRule.groovy
  src/test/groovy/org/prebid/server/functional/tests/BidAdjustmentSpec.groovy
  src/test/java/org/prebid/server/bidadjustments/BidAdjustmentsProcessorTest.java
  src/test/java/org/prebid/server/bidadjustments/BidAdjustmentsResolverTest.java
  src/test/java/org/prebid/server/bidadjustments/BidAdjustmentsRulesResolverTest.java
  src/test/java/org/prebid/server/bidadjustments/FloorAdjustmentsResolverTest.java
  src/test/java/org/prebid/server/bidadjustments/model/BidAdjustmentsRulesTest.java
Labels: do not port

#3979 Add ttd/thetradedesk alias
  src/main/resources/bidder-config/thetradedesk.yaml
Labels: do not port

#3964 Adnuntius Adapter: Add multi-format and native support
  src/main/java/org/prebid/server/bidder/adnuntius/AdnuntiusBidder.java
  src/main/java/org/prebid/server/bidder/adnuntius/model/request/AdnuntiusNativeRequest.java
  src/main/java/org/prebid/server/bidder/adnuntius/model/request/AdnuntiusRequest.java
  src/main/java/org/prebid/server/bidder/adnuntius/model/request/AdnuntiusRequestAdUnit.java
  src/main/java/org/prebid/server/bidder/adnuntius/model/response/AdnuntiusAdUnit.java
  src/main/java/org/prebid/server/bidder/adnuntius/model/response/AdnuntiusResponse.java
  src/main/java/org/prebid/server/spring/config/bidder/AdnuntiusBidderConfiguration.java
  src/main/resources/bidder-config/adnuntius.yaml
  src/test/java/org/prebid/server/bidder/adnuntius/AdnuntiusBidderTest.java
  src/test/java/org/prebid/server/it/AdnuntiusTest.java
  src/test/resources/org/prebid/server/it/openrtb2/adnuntius/test-adnuntius-bid-request.json
  src/test/resources/org/prebid/server/it/openrtb2/adnuntius/test-adnuntius-bid-response.json
  src/test/resources/org/prebid/server/it/openrtb2/adnuntius/test-auction-adnuntius-response.json
  src/test/resources/org/prebid/server/it/test-application.properties
Labels: do not port

#3910 Adjust Floors for Bidadjustments
  src/main/java/org/prebid/server/auction/BidsAdjuster.java
  src/main/java/org/prebid/server/auction/ExchangeService.java
  src/main/java/org/prebid/server/auction/model/AuctionContext.java
  src/main/java/org/prebid/server/auction/model/BidderRequest.java
  src/main/java/org/prebid/server/auction/requestfactory/AuctionRequestFactory.java
  src/main/java/org/prebid/server/bidadjustments/BidAdjustmentFactorResolver.java
  src/main/java/org/prebid/server/bidadjustments/BidAdjustmentRulesValidator.java
  src/main/java/org/prebid/server/bidadjustments/BidAdjustmentsEnricher.java
  src/main/java/org/prebid/server/bidadjustments/BidAdjustmentsProcessor.java
  src/main/java/org/prebid/server/bidadjustments/BidAdjustmentsResolver.java
  src/main/java/org/prebid/server/bidadjustments/BidAdjustmentsRetriever.java
  src/main/java/org/prebid/server/bidadjustments/BidAdjustmentsRulesResolver.java
  src/main/java/org/prebid/server/bidadjustments/FloorAdjustmentFactorResolver.java
  src/main/java/org/prebid/server/bidadjustments/FloorAdjustmentsResolver.java
  src/main/java/org/prebid/server/bidadjustments/model/BidAdjustments.java
  src/main/java/org/prebid/server/bidadjustments/model/BidAdjustmentsRule.java
  src/main/java/org/prebid/server/bidadjustments/model/BidAdjustmentsRules.java
  src/main/java/org/prebid/server/floors/BasicPriceFloorAdjuster.java
  src/main/java/org/prebid/server/floors/BasicPriceFloorEnforcer.java
  src/main/java/org/prebid/server/floors/NoSignalBidderPriceFloorAdjuster.java
  src/main/java/org/prebid/server/floors/PriceFloorAdjuster.java
  src/main/java/org/prebid/server/proto/openrtb/ext/request/ExtRequestBidAdjustments.java
  src/main/java/org/prebid/server/spring/config/PriceFloorsConfiguration.java
  src/main/java/org/prebid/server/spring/config/ServiceConfiguration.java
  src/main/java/org/prebid/server/util/dsl/config/impl/MostAccurateCombinationStrategy.java
  src/test/groovy/org/prebid/server/functional/model/request/auction/BidAdjustmentRule.groovy
  src/test/groovy/org/prebid/server/functional/model/request/auction/BidRequest.groovy
  src/test/groovy/org/prebid/server/functional/model/response/auction/Bid.groovy
  src/test/groovy/org/prebid/server/functional/model/response/auction/BidMediaType.groovy
  src/test/groovy/org/prebid/server/functional/service/PrebidServerService.groovy
  src/test/groovy/org/prebid/server/functional/testcontainers/PbsConfig.groovy
  src/test/groovy/org/prebid/server/functional/testcontainers/scaffolding/CurrencyConversion.groovy
  src/test/groovy/org/prebid/server/functional/tests/BaseSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/BidAdjustmentSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/CurrencySpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/StoredResponseSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsAdjustmentSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsBaseSpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsCurrencySpec.groovy
  src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsSignalingSpec.groovy
  src/test/groovy/org/prebid/server/functional/util/CurrencyUtil.groovy
  src/test/java/org/prebid/server/auction/BidsAdjusterTest.java
  src/test/java/org/prebid/server/auction/ExchangeServiceTest.java
  src/test/java/org/prebid/server/auction/requestfactory/AuctionRequestFactoryTest.java
  src/test/java/org/prebid/server/bidadjustments/BidAdjustmentFactorResolverTest.java
  src/test/java/org/prebid/server/bidadjustments/BidAdjustmentRulesValidatorTest.java
  src/test/java/org/prebid/server/bidadjustments/BidAdjustmentsEnricherTest.java
  src/test/java/org/prebid/server/bidadjustments/BidAdjustmentsProcessorTest.java
  src/test/java/org/prebid/server/bidadjustments/BidAdjustmentsResolverTest.java
  src/test/java/org/prebid/server/bidadjustments/BidAdjustmentsRulesResolverTest.java
  src/test/java/org/prebid/server/bidadjustments/FloorAdjustmentFactorResolverTest.java
  src/test/java/org/prebid/server/bidadjustments/FloorAdjustmentsResolverTest.java
  src/test/java/org/prebid/server/bidadjustments/model/BidAdjustmentsRulesTest.java
  src/test/java/org/prebid/server/floors/BasicPriceFloorAdjusterTest.java
  src/test/java/org/prebid/server/floors/BasicPriceFloorEnforcerTest.java
  src/test/java/org/prebid/server/floors/NoSignalBidderPriceFloorAdjusterTest.java
Labels: do not port

#3983 Test: Internal cache destination config
  src/test/groovy/org/prebid/server/functional/tests/CacheSpec.groovy
Labels: tests

#3833 Tests: Record a default core bid ranking
  src/test/groovy/org/prebid/server/functional/model/config/AccountAuctionConfig.groovy
  src/test/groovy/org/prebid/server/functional/model/config/AccountRankingConfig.groovy
  src/test/groovy/org/prebid/server/functional/model/response/auction/Bid.groovy
  src/test/groovy/org/prebid/server/functional/model/response/auction/Prebid.groovy
  src/test/groovy/org/prebid/server/functional/tests/TargetingSpec.groovy
Labels: tests

#4009 Fix flaky functional test
  src/test/groovy/org/prebid/server/functional/testcontainers/scaffolding/Bidder.groovy
  src/test/groovy/org/prebid/server/functional/tests/TargetingSpec.groovy
Labels: tests, do not port

#4015 Prebid Server prepare release 3.27.0
  extra/bundle/pom.xml
  extra/modules/confiant-ad-quality/pom.xml
  extra/modules/fiftyone-devicedetection/pom.xml
  extra/modules/greenbids-real-time-data/pom.xml
  extra/modules/ortb2-blocking/pom.xml
  extra/modules/pb-request-correction/pom.xml
  extra/modules/pb-response-correction/pom.xml
  extra/modules/pb-richmedia-filter/pom.xml
  extra/modules/pom.xml
  extra/pom.xml
  pom.xml
Labels: dependencies, do not port
